WIP: MinGW build support
TheAssemblyArmada/Vanilla-Conquer pull request #10
Opened 2020-06-16 17:42 UTC by hifi

Adds universal MinGW/gcc build support for all targets.

This still needs work, only TD targets build now.

2020-06-16 21:17 UTC, OmniBlade requested changes
I realise this is WIP, just a few things I noticed that you might or might not already have on your radar.

2020-06-16 21:17 UTC, OmniBlade commented on redalert/ftimer.h
> +    if (this->Started != 0xFFFFFFFFU) {
Personally I think a better fix to the strict lookup rules is adding `using` directives to the class as seen here https://github.com/OmniBlade/Chronoshift/blob/b20acda5f8c20d8512bd916a51aa80828b0c186f/src/game/common/ttimer.h#L87. That way you have to touch less lines of code.

2020-06-16 21:17 UTC, OmniBlade commented on CMakeLists.txt
> +if(WIN32)
Should probably be gated on MSVC, not WIN32 which I assume is still set for mingw.

2020-06-16 21:17 UTC, OmniBlade commented on redalert/function.h
> +#ifdef __MINGW32__
Could add the NOMINMAX macro and define it for all targets unconditionally? Ideally we move to std::min/max down the road anyhow for the C++ code.

2020-06-16 21:17 UTC, OmniBlade commented on tiberiandawn/vector.h
> +        if ((this->IsAllocated || !this->VectorMax) && GrowthStep > 0) {
Another case where we could use `using` directives in the class?

2020-06-17 18:40 UTC, hifi commented on CMakeLists.txt
> +if(WIN32)
Yeah, that should be fixed now

2020-06-17 18:45 UTC, hifi commented on redalert/function.h
> +#ifdef __MINGW32__
Fine for me, need to do that

2020-06-18 21:33 UTC, hifi commented on CMakeLists.txt
> +if(WIN32)
That's actually wrong, `WIN32` is not defined for MinGW so this works. We don't yet know our compiler at that point so `MSVC` is not defined as it's based on compiler detection.

Need to dig a bit further.

2020-06-18 21:35 UTC, hifi commented on tiberiandawn/vector.h
> +        if ((this->IsAllocated || !this->VectorMax) && GrowthStep > 0) {
This didn't actually work in my naive attempt in this case. It caused inheritance issues.

2020-06-18 21:37 UTC, hifi commented on CMakeLists.txt
> +if(WIN32)
One solution would be to gate just the assembler stuff behind `WIN32` and set the other stuff after the compiler has been detected with `MSVC`?

2020-06-19 18:02 UTC, hifi commented
RA is still grayscale on MinGW, uh oh.

2020-06-19 22:07 UTC, OmniBlade approved these changes

2020-06-21 11:40 UTC, hifi commented
Narrowed this down to fixed 1/2 not being initialized before OptionsClass constructor. Fixing this seems to require writing constexpr initializers for static helpers.

Not sure if it's just lucky on MSVC the fixed type gets initialized first or if there's a guaranteed static initialization order.

2020-06-22 05:32 UTC, merged