Cleanup more use of the "long" data type.
TheAssemblyArmada/Vanilla-Conquer pull request #1012
Opened 2024-06-21 09:25 UTC by OmniBlade

This datatype varies in length between platforms so its use is not portable.

2024-06-23 14:52 UTC, giulianobelinassi requested changes

2024-06-23 14:52 UTC, giulianobelinassi commented on redalert/conquer.cpp
> +                sprintf(buffer, "Ins�rez le %s", _cd_name[cd]);
Looks like this change was done by mistake.

2024-06-23 14:52 UTC, giulianobelinassi commented on redalert/conquer.cpp
> +                sprintf(buffer, "Ins�rez le %s", _cd_name[4]);
Looks like this change was done by mistake.

2024-06-23 14:52 UTC, giulianobelinassi commented on redalert/jshell.cpp
>      return (256L + (256L * count));
Still long constants

2024-06-23 14:52 UTC, giulianobelinassi commented on redalert/netdlg.cpp
> - *    �  ���������������������������������������   �                                           *
Looks like this change was done by mistake.

2024-06-23 14:52 UTC, giulianobelinassi commented on tiberiandawn/jshell.cpp
>      return (256L + (256L * count));
Still long constants.

2024-06-23 14:52 UTC, giulianobelinassi commented on tiberiandawn/logic.cpp
> +                "�Terrain...�   �                                         �\r"
Looks like this change was done by mistake.

2024-06-23 14:52 UTC, giulianobelinassi commented
There are changes which seems to have been done by mistake automatically by your text editor.

2024-06-24 08:33 UTC, OmniBlade commented
Should all be cleaned up now.

2024-06-24 13:11 UTC, giulianobelinassi requested changes

2024-06-24 13:11 UTC, giulianobelinassi commented on redalert/conquer.cpp
> +        int minx = 0x7FFFFFFFL, miny = 0x7FFFFFFFL;
long constant

2024-06-24 13:11 UTC, giulianobelinassi commented on redalert/dllinterface.cpp
> +    int minx = 0x7FFFFFFFL, miny = 0x7FFFFFFFL;
long constant

2024-06-24 13:11 UTC, giulianobelinassi commented on tiberiandawn/aircraft.cpp
> +                "�Discovered....� � �Timer:�Arm:������������������Flash:�Stage:�Team:�����Arch:�\n"
Mistake change

2024-06-24 13:11 UTC, giulianobelinassi commented on tiberiandawn/function.h
> +        � ScrollClass-- map scroll handler
mistake change

2024-06-24 13:11 UTC, giulianobelinassi commented on tiberiandawn/function.h
> +        � SidebarClass-- displays and controls construction list sidebar
mistake change

2024-06-24 13:11 UTC, giulianobelinassi commented on tiberiandawn/function.h
> +        � MapClass-- general tactical map data handler
mistake change

2024-06-24 13:11 UTC, giulianobelinassi commented on tiberiandawn/function.h
> +                                  �
mistake change

2024-06-24 13:11 UTC, giulianobelinassi commented on tiberiandawn/function.h
> +             � TemplateTypeClass         �
mistake change

2024-06-24 13:30 UTC, OmniBlade commented
Aw man, that stupid utf conversion :D

2024-06-25 08:52 UTC, OmniBlade commented
Okay, really should be cleaned up this time @giulianobelinassi

2024-06-25 12:43 UTC, giulianobelinassi requested changes

2024-06-25 12:43 UTC, giulianobelinassi commented on redalert/conquer.cpp
> +                sprintf(buffer, "Ins�rez le %s", _cd_name[cd]);
Mistake change

2024-06-25 12:43 UTC, giulianobelinassi commented on redalert/conquer.cpp
> +                sprintf(buffer, "Ins�rez le %s", _cd_name[4]);
Mistake change

2024-06-25 13:39 UTC, OmniBlade commented on redalert/conquer.cpp
> +                sprintf(buffer, "Ins�rez le %s", _cd_name[cd]);
I think these are actually fixing a change that went through incorrectly previously.

2024-06-26 02:54 UTC, giulianobelinassi approved these changes

2024-06-26 08:14 UTC, merged