Fix SC* expansion files not caching on none windows.
TheAssemblyArmada/Vanilla-Conquer pull request #1014
Opened 2024-06-22 22:00 UTC by OmniBlade

Fixes any mod or expansion that relied on cached resources.
Fixes #734

2024-06-23 10:25 UTC, hazelnot commented
Checked it out in-game. Game doesn't crash anymore, and the tile gets rendered!

2024-06-23 14:44 UTC, giulianobelinassi requested changes

2024-06-23 14:44 UTC, giulianobelinassi commented on common/file.cpp
> +        strncpy(fname, ffblk->GetFullName(), strlen(fname) + 1);
Store the value of `strlen` into a variable to avoid recomputing its value.

2024-06-23 14:44 UTC, giulianobelinassi commented on common/file_win.cpp
> +    virtual const char* GetFullName() const
Why don't implement this method as returning `nullptr` on the base class, and only implement it on Linux? That way we do not have to provide an implementation always returning `nullptr` for Windows.

2024-06-24 13:13 UTC, giulianobelinassi approved these changes

2024-06-24 13:13 UTC, merged