Mouse platform dependent stuff abstraction
TheAssemblyArmada/Vanilla-Conquer pull request #114
Opened 2020-08-10 21:50 UTC by wdigger

2020-08-10 22:16 UTC, wdigger commented
Hm.. Something wrong with MinGW linking.

2020-08-11 06:35 UTC, hifi commented
Do we need an abstraction here (other than mouse disabled) because when the windowing is changed from winapi to SDL2 it will also switch the mouse implementation at the same time which will be platform independant?

2020-08-11 10:07 UTC, wdigger commented
In this case Remaster is a some kind of platform.
Main mouse related code have no ifdefs at all, it's a main reason for this move.

2020-08-11 11:15 UTC, OmniBlade commented
@hifi That was my intial reaction when I first looked at this PR, in my mind, WWMouseClass IS the abstraction layer for the rest of the program, so a few ifdefs in its header and separate implementation cpp files would be my expectation. Alternatively, since WWMouseClass is allocated in main anyhow, make WWMouseClass a pure virtual abstraction and create implementations under it rather than having the two levels of abstraction this will leave us with? @wdigger Thoughts?

2020-08-11 12:33 UTC, wdigger commented
I don’t believe you’re ready to remove the native implementation after the new one is ready (SDL?), so it’s better to be able to switch implementations with a minimal platform-specific part.

2020-08-11 13:03 UTC, OmniBlade commented
You could switch implementations with my proposal, change WWMouseClass to use a virtual interface with pure virtual for any functions that needs platform specific code, then implement WWWinMouseClass, WWRemasterMouseClass, WWSDLMouseClass... etc derived from WWMouseClass rather than having an interface that the interface class uses. Change the allocation of WWMouseClass in WinMain to be a call to a new WWMouseClass::Create() function and we probably don't need many more changes than that.

2020-08-11 16:02 UTC, hifi commented
I think we could live with a single mouse implementation that has ifdefs for remaster and it would be completely replaced by the SDL2 version when windowing is switched to it. It's not like getting the cursor position is a complex thing in either implementation.

2020-08-11 19:10 UTC, wdigger commented
@OmniBlade I have implemented your vision.

2020-08-13 18:45 UTC, hifi requested changes
While there is good intention here I think it can be simplified a lot.

2020-08-13 18:45 UTC, hifi commented on common/shape.h
> +typedef struct Shape_Type : Shape_Header
Why?

2020-08-13 18:45 UTC, hifi commented on common/wwmousedrawable.h
> +    void* ASM_Set_Mouse_Cursor(int hotspotx, int hotspoty, void* cursor);
Maybe we could drop the `ASM_` prefix now that these are properly refactored into the class.

2020-08-13 18:45 UTC, hifi commented on common/wwmousedrawable.h
> +class WWMouseClassDrawable : public WWMouseClass
Is this class necessary? Even when remaster doesn't really draw the mouse this seems like a useless abstraction.

2020-08-13 18:45 UTC, hifi commented on common/wwmouse_remaster.cpp
> +class WWMouseClassRemaster : public WWMouseClass
Can't this just be the "null" mouse to begin with with remaster ifdefs? Too much abstraction here for about six lines of code for the remaster.

2020-08-13 19:08 UTC, wdigger commented on common/shape.h
> +typedef struct Shape_Type : Shape_Header
Asm code used struct size for some calculations.

2020-08-13 19:09 UTC, wdigger commented on common/wwmousedrawable.h
> +class WWMouseClassDrawable : public WWMouseClass
Win and SDL are drawing both.

2020-08-13 19:17 UTC, wdigger commented on common/wwmouse_remaster.cpp
> +class WWMouseClassRemaster : public WWMouseClass
As I said before, I consider remaster to be another platform.
Such a statement saves us from superfluous and incomprehensible concept, named "remaster".

2020-08-13 19:17 UTC, wdigger commented on common/wwmousedrawable.h
> +    void* ASM_Set_Mouse_Cursor(int hotspotx, int hotspoty, void* cursor);
Yep

2020-08-13 19:21 UTC, wdigger commented on common/shape.h
> +typedef struct Shape_Type : Shape_Header
Structs (class as struct) redefinition is a common place for this project.

2020-08-13 19:56 UTC, wdigger commented on common/wwmouse_remaster.cpp
> +class WWMouseClassRemaster : public WWMouseClass
I think that later it is worth removing the rendering of the cursor completely and using the system one, this will greatly simplify the entire rendering (now the rendering of the cursor interrupts the rendering of everything else with the critical section).

2020-08-13 19:58 UTC, wdigger commented on common/wwmousedrawable.h
> +    void* ASM_Set_Mouse_Cursor(int hotspotx, int hotspoty, void* cursor);
Done

2020-08-13 21:34 UTC, OmniBlade commented on common/wwmouse_remaster.cpp
> +class WWMouseClassRemaster : public WWMouseClass
System cursor won't scale if we decide to add scaling filter options at some point in the future so software cursor needs to remain an option for standalone IMO. Also, while wasteful, its not like even ancient systems struggled to cope with drawing the software cursor.

2020-08-13 21:37 UTC, OmniBlade commented on common/shape.h
> +typedef struct Shape_Type : Shape_Header
Nothing else in the game uses the old Dune2 shape format besides the mouse, all these functions and definitions relating to it can probably be moved wholesale to the mouse classes. Some stuff is still needed for the drawing of the C&C shape format like the draw style enums so they need to remain shared or moved to only support the new shapes.

2020-08-15 05:01 UTC, hifi commented on common/wwmouse_remaster.cpp
> +class WWMouseClassRemaster : public WWMouseClass
Indeed. We can never really use system cursors.

The proper fix for the cursor drawing code is to make the engine draw it on the frame every time a frame is rendered as the last thing instead of having a separate thread rendering it on its own. This is how most games work that do 2D blitting.

2020-08-15 05:02 UTC, hifi commented on common/wwmousedrawable.h
> +class WWMouseClassDrawable : public WWMouseClass
So keep it part of WWMouseClass then.

2020-08-15 12:11 UTC, wdigger commented
No chance.

2020-08-15 12:11 UTC, closed without merging