Implements C++ version of Put_Fat_Pixel from TD.
TheAssemblyArmada/Vanilla-Conquer pull request #117
Opened 2020-08-11 13:44 UTC by OmniBlade

Test is WIP as GraphicBufferClass doesn't link with just the code from common, so cannot actually test the blitter against the ASM for now.

2020-08-13 18:32 UTC, hifi requested changes

2020-08-13 18:32 UTC, hifi commented on tests/fatpixel.cpp
> +        if (0 /*memcmp(basebuff, image_data, image_data_length) != 0*/) {
I'm not sure if this is still WIP but pointing this out since you requested a review :grin:

2020-08-13 19:32 UTC, OmniBlade commented on tests/fatpixel.cpp
> +        if (0 /*memcmp(basebuff, image_data, image_data_length) != 0*/) {
The test is a prototype but won't build or work as it stands. I can omit it completely from the PR, but I wanted the skeleton of the test at least in place. What do you think?

2020-08-15 04:35 UTC, hifi commented on tests/fatpixel.cpp
> +        if (0 /*memcmp(basebuff, image_data, image_data_length) != 0*/) {
What is the blocker to get the test working?

2020-08-15 14:00 UTC, OmniBlade commented on tests/fatpixel.cpp
> +        if (0 /*memcmp(basebuff, image_data, image_data_length) != 0*/) {
GraphicsBufferClass doesn't appear to link with just the code from common... not sure what else is needed though.

2020-08-18 22:46 UTC, OmniBlade commented on tests/fatpixel.cpp
> +        if (0 /*memcmp(basebuff, image_data, image_data_length) != 0*/) {
I've pulled the WIP test code for now since it didn't even have test data available yet. Can look at testing these ASM translations that need GraphicBufferClass at a later date as a verification pass before removing the ASM code for them entirely?

2020-08-26 22:40 UTC, OmniBlade commented
Now with added working tests.

2020-08-29 05:08 UTC, hifi approved these changes

2020-08-31 22:03 UTC, merged