Greatly reduces the CPU use of the game.
TheAssemblyArmada/Vanilla-Conquer pull request #128
Opened 2020-08-21 22:07 UTC by OmniBlade

Adds a liberal sprinkling of sleep across the games many busy wait loops.

Subject to testing it fixes the following bugs:
Fixes #60 
Fixes #91 
Fixes #119 

The fixes to the mysterious sound crash are probably due to the new delays masking whatever race condition led to it.

Also fixes the scroll rate being far too fast without needing interventions from a ddraw.dll.

2020-08-21 22:43 UTC, ghost commented on redalert/conquer.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(1));
Not sure if you wanna add mutex here for `FrameTimer`. (Check body of loop above)

Then you would need to remember:
```
while (true) {
  {
  // here set mutex
  // and do stuff
  }
  // here sleep
}

```

2020-08-21 22:51 UTC, OmniBlade commented
Looks like we might need https://github.com/meganz/mingw-std-threads or to select a different version of mingw on the CI.

2020-08-21 22:55 UTC, OmniBlade commented on redalert/conquer.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(1));
Not sure what the concern is that might need a mutex, some potential race condition I'm not seeing?

2020-08-21 23:54 UTC, ghost commented on redalert/conquer.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(1));
I'm kinda not sure about global instance `FrameTimer`, if it's used by more than one thread.

2020-08-22 04:57 UTC, hifi commented
Shouldn't we instead of adding random sleeps around the engine add a function call to a proper frame limiter?

2020-08-22 05:30 UTC, hifi commented on redalert/conquer.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(1));
The game doesn't really do threading that much. There's that winmm timer callback thing for sound and mouse code but other than that it runs single threaded. @OmniBlade said this is probably a remnant of how the DOS code used interrupts to trigger the updates.

It would be great if we could completely remove those and make this run single threaded in the long run as it will also simplify and remove those possible race conditions.

2020-08-22 20:28 UTC, OmniBlade commented
Well they are added where an eventual flip/draw call will need to be made when ported to a graphics api that doesn't pretend you have direct access to the frame buffer anymore, so I'd say more fine grained frame limiting should be implemented with that piece of work.

This at least marks most of the points in the game engine where such things will need to be considered for later refactoring and greatly improves the behaviour of the engine on a multitasking OS. Its just a bonus that it seems to fix the sound engine crashes.

I've refactored the PR to use win32 Sleep on windows and Posix nanosleep on none windows for now to avoid the issues with std::thread and mingw.

2020-08-26 21:01 UTC, OmniBlade commented
I've updated the PR with an attempt at a frame limiter that should try and keep the refresh rate around 120 fps which should be more than enough. Game runs fine for me with close to 0% CPU use for most situations rather than near 100% on one core.

2020-08-27 05:10 UTC, hifi requested changes
PR looks good otherwise but the unintentional in-game text changes need to be reverted.

2020-08-27 05:10 UTC, hifi commented on redalert/expand.cpp
> -                           "Molekulare Kriegsf�hrung",      //	"SCG48EA",		// Absolut MADness
Your editor got caught up with these. We should do a PR that converts all of this into escape sequences.

2020-08-27 20:43 UTC, OmniBlade commented on redalert/expand.cpp
> -                           "Molekulare Kriegsf�hrung",      //	"SCG48EA",		// Absolut MADness
Second time its done that to me and I had to revert it. Fixed now.

2020-08-29 05:07 UTC, hifi approved these changes

2020-08-30 19:35 UTC, merged