Initial SDL2 support
TheAssemblyArmada/Vanilla-Conquer pull request #175
Opened 2020-10-30 06:58 UTC by hifi

This is a cleaned up version of the branch I've been using to test on Linux. Using scancodes and the location for the event pump has been taken from @LasDesu fork.

I think this this has the smallest impact in the common code I can think of.

Thank you for @LasDesu for the cleaned up version of some of my hacks.

2020-10-30 12:25 UTC, hifi commented
Only targets that can be built are built on non-Windows by default, means VanillaTD only without sound.

2020-10-30 18:11 UTC, tomsons26 commented on common/framelimit.cpp
> +#ifdef SDL2_BUILD
This def isn't the right place for this

2020-10-30 18:15 UTC, hifi commented on common/framelimit.cpp
> +#ifdef SDL2_BUILD
The SDL2 path intentionally draws the cursor just before the frame is flipped. I intend to remove the async mouse drawing code completely if it has no performance penalty.

2020-10-31 23:24 UTC, OmniBlade requested changes

2020-10-31 23:24 UTC, OmniBlade commented on common/wwkeyboard.cpp
> +#include <SDL2/SDL.h>
Need to just use `#include <SDL.h>` as some platforms don't keep the includes for it in `SDL2/`. Standard windows package certainly doesn't.

2020-10-31 23:24 UTC, OmniBlade commented on common/CMakeLists.txt
> +    list(APPEND VANILLA_LIBS ${SDL2_LIBRARY})
Just append the SDL2::SDL2 target instead of ${SDL2_LIBRARY} and skip setting the include directories globally for it as the target passes them along based on the FindSDL2 cmake module.

2020-10-31 23:24 UTC, OmniBlade commented on common/CMakeLists.txt
> +    target_compile_definitions(common PUBLIC SDL2_BUILD)
This will break the remaster build on windows as its sets it for common, not just commonv. The files that need differentially compiling will probably need to be built in the commonr/commonv targets or we may need to rebuild common entirely for both targets.

2020-10-31 23:24 UTC, OmniBlade commented on common/wwkeyboard.h
> +#define VK_NONE SDL_SCANCODE_UNKNOWN
MSVC complains a lot about these being redefined.

2020-10-31 23:34 UTC, OmniBlade requested changes
Got it building with the suggested changes in msvc. TD runs but mouse doesn't update on menus, once in game it seems to run fine.

2020-10-31 23:34 UTC, OmniBlade commented on common/video_sdl2.cpp
> +    unsigned char* rcolors = rpalette;
Need a cast here for C++ which doesn't allow implict assignment from void *.

2020-10-31 23:34 UTC, OmniBlade commented on common/wwkeyboard.cpp
> +    buffer[0] = SDL_GetKeyFromScancode(key);
MSVC wants the key value cast explictly to the enum type for key.

2020-11-01 07:30 UTC, hifi commented on common/wwkeyboard.h
> +#define VK_NONE SDL_SCANCODE_UNKNOWN
Added a definition to skip those when including winuser.h

2020-11-01 09:08 UTC, hifi commented on common/CMakeLists.txt
> +    list(APPEND VANILLA_LIBS ${SDL2_LIBRARY})
I couldn't get that to work properly for some reason, what did you change exactly? The latest iteration compiles for me on Windows now

2020-11-01 09:09 UTC, hifi commented on common/CMakeLists.txt
> +    target_compile_definitions(common PUBLIC SDL2_BUILD)
Probably splitting more files between remaster/vanilla common is the correct way forward. If it's starting to make more sense to compile common completely separately then we should do that.

2020-11-01 23:14 UTC, OmniBlade commented
Okay, latest push builds TD okay on windows with MSVC. The cursor now moves on the menu, but the wsa for the side select is stuck on the first frame now (worked before) and some vqa videos play too fast. Not sure if you want to consider those deal breaking for the initial SDL port or not.

2020-11-02 11:09 UTC, OmniBlade commented on common/CMakeLists.txt
> +    target_compile_definitions(common PUBLIC SDL2_BUILD)
I tested moving the define to just commonv and that appeared to let everything build though I didn't actually test any of the resulting code.

2020-11-03 05:45 UTC, hifi commented
If the stock ddraw version works without any issues I'd like this merged sooner than later so work can continue on 64-bit support and fixing up the rendering path a bit.

The way the SDL2 surface is flipped on every lock/unlock of the front buffer has a huge performance penalty which has always been apparent on Wine with the original games (hence why cnc-ddraw was born) but it's something that should be easy to fix later. My desktop CPU/GPU combo is fast enough it's hard to notice these things but on a low power ARM64 laptop I could see the TD main menu drawing one button at a time :smile:

2020-11-03 10:14 UTC, OmniBlade approved these changes

2020-11-03 10:19 UTC, merged