Changes to make it compile on osx (brew)
TheAssemblyArmada/Vanilla-Conquer pull request #231
Opened 2020-12-18 02:05 UTC by capsterx

1) override c++ (clang) for gcc, as clang had more warnings/errors I did not want to fix
2) by default it picks up openal as a framework, override this for brew version.
3) Looks like the osx linker checks dependencies for things that are not referred to, so red alert had a lot of warnings of things that look deprecated but still defined (and reference undefined code).
4) minor changes to not include malloc.h

2020-12-18 09:11 UTC, OmniBlade requested changes
Thanks for this PR, its good to see we aren't too far from being able to compile on macOS. I think from our point of view we would rather not hard code things like the compiler and library paths if at all avoidable and instead push it into the documentation for a given platform to support people building the code. Hopefully as we clean up the code base more th GCC requirement will go away and we can use Clang instead for example.

2020-12-18 09:11 UTC, OmniBlade commented on common/alloc.cpp
> +#ifndef __APPLE__
You can probably just remove the `malloc.h` include alltogether as the standard says malloc and friends are supposed to be provided by `stdlib.h` anyway.

2020-12-18 09:11 UTC, OmniBlade commented on CMakeLists.txt
> +  set(OPENAL_LIBRARY /usr/local/opt/openal-soft/lib/libopenal.1.21.0.dylib)
Changing the preferred OpenAL to link against should probably be done by passing -DOPENAL_ROOT=/usr/local/opt/openal-soft to cmake at configure time rather than hard coding it. Does it not work correctly against the system OpenAL?

2020-12-19 07:31 UTC, hifi commented
Opened #232 which should fix all code compatibility issues in a mergeable way.

I think we can fix clang on Linux to get macOS to work as well. I'd rather not enforce the compiler in CMakeLists.

2020-12-20 02:25 UTC, closed without merging

2020-12-20 02:25 UTC, capsterx commented
Using a different codebase