Osx and clang fixes
TheAssemblyArmada/Vanilla-Conquer pull request #235
Opened 2020-12-20 02:33 UTC by capsterx

This should fix both osx and clang builds
Things clang does not do that gcc allows

Template functions resolving without this->
Allowing taking a reference to a temporary
It really will not allow you to truncate a pointer to a short, so cast to uintptr_t before truncating
It does not auto instantiate the constructor when explicitly  instantiating the class.
I'm not even sure how WWMessageBox().Process was being allowed to called by gcc as it was missing parameters
gcc allows Class:: inside a class definition
gcc allows one to redefine a prototype not declared static to be static later

Minor fixes:
remove malloc.h references because it breaks osx
cast void* ptr to char* when calling delete[] otherwise it will redirect to delete()
Changes to arguments for OSX so it will compile
 * no -static-libstdc++ -static-libgcc or -Wl,--gc-sections

2020-12-20 07:44 UTC, hifi requested changes
This PR was opened after #232 was merged and #234 already existed with half of the fixes already so this will not be mergeable anymore and only contains a few lines that are missing from the other PRs.

However I reviewed this for feedback purposes and I picked up a few changes from this to #234 that I didn't figure out myself so huge thanks for that.

I hope you don't feel I steamrolled your PRs but when you initially opened the Switch/macOS PR I wanted to get the issues fixed ASAP and immediately started working on getting them cleaned up for inclusion.

2020-12-20 07:44 UTC, hifi commented on CMakeLists.txt
> +      set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wl,--gc-sections")
After #232 was merged, we don't need `--gc-sections` anymore

2020-12-20 07:44 UTC, hifi commented on CMakeLists.txt
> +      set(STATIC_LIBS "-static-libstdc++ -static-libgcc")
This was only needed for MinGW builds so it is moved inside `if(WIN32)` in #234

2020-12-20 07:44 UTC, hifi commented on common/buff.cpp
> +            delete[] (char*)BufferPtr;
I did not see this being an issue on Linux clang, does this only affect macOS?

2020-12-20 07:44 UTC, hifi commented on common/ccfile.cpp
> +/***********************************************************************************************
I moved these into `load.cpp` where there is another definition if them in #234 

I did use your implementation of constifying the argument to get the compiler to like the reference.

2020-12-20 07:44 UTC, hifi commented on common/int.h
> +    friend Int<PRECISION> Generate_Prime(Straw& rng, int pbits, Int<PRECISION> const* dummy);
We determined this was some sort of compiler hack in the Watcom days and removed the argument completely in #232

2020-12-20 07:44 UTC, hifi commented on redalert/ccptr.cpp
> +template CCPtr<AircraftClass>::CCPtr(AircraftClass *);
This was a really good fix, I was stumped what clang wanted!

I added these to #234, thanks!

2020-12-20 07:44 UTC, hifi commented on redalert/drop.h
> +    , List(0, x, y + this->Get_Build_Frame_Height(down), w + this->Get_Build_Frame_Width(down), h, flags, up, down)
This is wrong, `Get_Build_Frame_*` functions are not member functions and the compiler gets confused when they don't have a definition.

I fixed these in #232 by adding the missing include.

2020-12-20 07:44 UTC, hifi commented on redalert/drop.h
> +    List.Set_Position(x, y + this->Get_Build_Frame_Height(DropButton.Get_Shape_Data()));
Ditto, see above.

2020-12-20 07:44 UTC, hifi commented on redalert/list.h
> +    this->Fancy_Text_Print(TXT_NONE, 0, 0, nullptr, TBLACK, TextFlags);
Ditto, see above.

2020-12-20 07:44 UTC, hifi commented on tiberiandawn/iomap.cpp
> +        OccupierPtr = As_Object((TARGET)(uintptr_t)OccupierPtr, false);
Did the exact same thing in #234 but wrapped in a macro if this is changed later to something that doesn't lose precision.

2020-12-20 14:43 UTC, capsterx commented on common/buff.cpp
> +            delete[] (char*)BufferPtr;
It compiles fine on both, but delete[] void* ends up calling delete, which valgrind can detect as a mismatched new[]/delete.  I looked it up and delete[] void* is basically invalid, same as you cannot new[] void.

2020-12-20 19:37 UTC, hifi commented on common/buff.cpp
> +            delete[] (char*)BufferPtr;
Was this the only mismatched new/delete that valgrind spotted that was ringing bells? It would be better to separate fixes like this into another PR that focuses on them.

2020-12-22 04:58 UTC, hifi commented
@capsterx can you please try with the latest vanilla branch if it builds properly now? Thanks.

2020-12-23 00:36 UTC, capsterx commented
> @capsterx can you please try with the latest vanilla branch if it builds properly now? Thanks.

Yes, but because of the use of enum types ex:
/common/./wwstd.h:198:14: error: expected identifier or '{'
typedef enum : unsigned short

it requires -std=c++11 (or above) to compile

Other than that it compiles clean.

2020-12-24 19:38 UTC, hifi commented
Closing this in favor of already merged PRs and #290. Thanks!

2020-12-24 19:38 UTC, closed without merging