Adds CCINIClass to TD and refactors scenario loading code to use it.
TheAssemblyArmada/Vanilla-Conquer pull request #282
Opened 2020-12-21 23:46 UTC by OmniBlade

CCINIClass contains specialised routines for parsing certain data types from an INI file and was introduced in RA. This means the INI reading and writing code for object classes doesn't need to duplicate this code for certain types. By refactoring the scenario loading code to use the new TD version of this class, we bring the code more in line with RA code and lay the basis for more improvements such as rules.ini for TD.

2020-12-25 17:35 UTC, hifi requested changes
Aside from the CRC stuff which I didn't really understand I didn't find anything else sticking out. And the stubs.

You added some NULL checks along the way which is good. I haven't yet tested playing with these changes but I've painstakingly read through everything with as much thought I could maintain while doing that.

Overall good work, need to do some play testing to make sure these work as intended at least for a few scenario maps.

2020-12-25 17:35 UTC, hifi commented on tiberiandawn/ccini.cpp
> +    return 0;
Would be better not to include stubs that are not used and return the incorrect data. When/if CCINIClass is merged to common we can add proper implementations and not ever accidentally use stubs.

So I would prefer to not have any functions in the class that are not used within TD but keep the same API for functions that are used by both games. This makes the class smaller and easier to grasp what's being actually used.

2020-12-25 17:35 UTC, hifi commented on tiberiandawn/scenarioini.cpp
> -        Add_CRC(&ScenarioCRC, (unsigned long)val);
I didn't see this being implemented anywhere, doesn't this mean that the CRC is never calculated?

2020-12-25 17:35 UTC, hifi commented on tiberiandawn/scenarioini.cpp
> -        Add_CRC(&ScenarioCRC, (unsigned long)val);
Ditto here.

2020-12-25 23:13 UTC, OmniBlade commented on tiberiandawn/scenarioini.cpp
> -        Add_CRC(&ScenarioCRC, (unsigned long)val);
This is true, the CCINIClass uses the SHA1 digest instead which would need to be used in place of the CRC check which I assume is just to check no one tampered with the map in MP games.

2020-12-27 22:43 UTC, OmniBlade commented on tiberiandawn/ccini.cpp
> +    return 0;
I've removed the implementations, do you want me to remove the prototypes as well?

2020-12-28 05:09 UTC, hifi commented on tiberiandawn/scenarioini.cpp
> -        Add_CRC(&ScenarioCRC, (unsigned long)val);
Would it work to fill the crc with a partial from the SHA digest so it at the least functions for its intended purpose? We can then replace it with the full digest once we touch the protocol.

2020-12-28 05:16 UTC, hifi commented on tiberiandawn/ccini.cpp
> +    return 0;
That would be great as well. Thanks.

2021-01-04 19:42 UTC, hifi approved these changes
I tested the game runs with these changes. Looks good enough to me now.

2021-01-04 23:03 UTC, merged