Set C++ standard version to C++11, C to C99
TheAssemblyArmada/Vanilla-Conquer pull request #290
Opened 2020-12-23 05:11 UTC by hifi

Based on comment on #231, set minimum required C++ standard to C++11. Also fix C to C99.

This may need discussion what our target C++ standard should really be but if we already depend on C++11 features and nothing newer (at least in the portable builds) I think it's fine for now.

2020-12-23 09:30 UTC, OmniBlade requested changes

2020-12-23 09:30 UTC, OmniBlade commented on CMakeLists.txt
> +    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -w -fcheck-new -fsigned-char -fdata-sections -ffunction-sections -DNOMINMAX")
Should really set them as follows rather than hardcoding them into the flags:
`set(CMAKE_CXX_STANDARD 11)`
`set(CMAKE_C_STANDARD 99)`

2020-12-23 09:42 UTC, wdigger commented
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

Or you have to guess the compiler and linker flags for all platforms, which is a long story.

2020-12-24 22:52 UTC, OmniBlade approved these changes

2020-12-25 07:57 UTC, merged