[RA] Refactors Force_CD_Available to add better no-cd support.
TheAssemblyArmada/Vanilla-Conquer pull request #297
Opened 2020-12-23 22:45 UTC by OmniBlade

Game will now search for main.mix in folders called allied, soviet, counterstrike and aftermath
when trying to detect a CD before performing an actual CD lookup.

If one folder is provided it will behave as if -CD was used and searching for actual physical CDs
will be disabled. To allow disk switching for access to all content all folders must be provided.

Fixes #291

2020-12-24 06:01 UTC, hifi commented
One thing I noticed in RA is that if you have MAIN.MIX in the root folder the game will ask you to insert a Red Alert CD but if you cancel the dialog it continues without issues.

2020-12-24 09:43 UTC, OmniBlade commented
I've not touched the message box code, the mouse release should probably be done in WWMessageBox::Process but that will affect any message boxes created by it. I've updated the PR with similar no-cd support for TD.

2020-12-24 10:02 UTC, hifi commented
Maybe not worth touching locking now. I need to refactor it completely at some point to work the other way around where we only lock it when in game.

2020-12-24 18:16 UTC, hifi requested changes
Okay, I retested and I still see these issues that need to be fixed on startup with RA:

MAIN.MIX in game dir -> Please insert a Red Alert CD-ROM
"allied" and "soviet" directories exist with MAIN.MIX -> Please insert a Red Alert CD-ROM

This doesn't solve no-cd if none of the supported combinations work out of the box.

2020-12-24 18:30 UTC, hifi commented
So anyway TD inhibits the same issue RA did before that CD mixes in the main game dir nags about the CD but hitting cancel still works. RA works completely fine in all supported configurations.

2020-12-24 23:27 UTC, OmniBlade commented
Updated so that having main.mix in ra and general.mix in td in the game directory will now not prompt for the CD.

2020-12-25 06:15 UTC, hifi commented
TD now works fine, I'm happy with this :+1:

2020-12-25 06:15 UTC, hifi approved these changes

2020-12-25 07:12 UTC, merged