WIP: Adds optional standalone builds.
TheAssemblyArmada/Vanilla-Conquer pull request #3
Opened 2020-06-05 22:25 UTC by OmniBlade

Adds an optional scenario editor build to the standalone builds.
Adds headers sections to MSVC for the benefit of windows developers.

2020-06-06 05:52 UTC, hifi commented
Sorry I had to reformat CMakeLists.txt with a force push, won't happen again. I rebased the tests branch on it.

2020-06-08 13:43 UTC, hifi requested changes

2020-06-08 13:43 UTC, hifi commented on CMakeLists.txt
> +    message(WARNING "Internal scenario editor requires Tiberian Dawn executable to be built, but it is not enabled.")
Only a warning? Though see later comment.

2020-06-08 13:43 UTC, hifi commented on CMakeLists.txt
> +if(MSVC)
Doesn't this prevent the options from even working at all if not MSVC?

2020-06-08 13:43 UTC, hifi commented on CMakeLists.txt
> +    if(MAP_EDITORRA)
Does this this need to be dependant on the main game? Can't it be be a completely independent target with the same source and different options?

2020-06-08 13:52 UTC, OmniBlade commented on CMakeLists.txt
> +if(MSVC)
> 
> 
> Doesn't this prevent the options from even working at all if not MSVC?

It does, the options won't exist and the code gated by the if won't be used. Do you want it to be possible to build the dll files with mingw? Probably need to test if they actually work with the remaster I guess and change it to WIN32 as the target if they do.

2020-06-08 13:52 UTC, OmniBlade commented on CMakeLists.txt
> +    if(MAP_EDITORRA)
The resulting binary is the full game, its not like edwin where its a separate program with separate behaviour. Its like an extra feature built into the game engine if that makes sense. We could build a separate build that includes the editor functionality, but it seems silly to.

2020-06-08 13:52 UTC, OmniBlade commented on CMakeLists.txt
> +    message(WARNING "Internal scenario editor requires Tiberian Dawn executable to be built, but it is not enabled.")
Probably should error I guess so the user knows they need to change something to get what they want or could force the building of the exe target if the editor is requested?

2020-06-08 13:55 UTC, hifi commented on CMakeLists.txt
> +if(MSVC)
Indeed, it would be a good smoke test for mingw to be able to build for remaster. It should also help setting up a build env on Windows if you prefer it over MSVC.

If possible I'd just have it OFF for non-Win32 by default instead of having the option completely missing so it's possible to force enable it for any reason.

2020-06-08 13:55 UTC, hifi commented on CMakeLists.txt
> +    if(MAP_EDITORRA)
Okay, that makes sense.

2020-06-08 13:57 UTC, hifi commented on CMakeLists.txt
> +    message(WARNING "Internal scenario editor requires Tiberian Dawn executable to be built, but it is not enabled.")
I'd probably prefer forcing the game option on with a warning text.

2020-06-09 03:36 UTC, hifi approved these changes

2020-06-09 03:36 UTC, hifi commented on CMakeLists.txt
> +if(WIN32 OR "${CMAKE_SYSTEM}" MATCHES "Windows")
If I can set `WIN32` from MinGW toolchain file this system check is superfluous. Need to check that out.

2020-06-09 03:40 UTC, merged