[RA] Fix mission and custom scenario search on Linux
TheAssemblyArmada/Vanilla-Conquer pull request #313
Opened 2020-12-26 07:44 UTC by hifi

This fixes listing custom MPR files in skirmish and presumably multiplayer for RA on non-Windows. Also cleaned up the ifdef and comment mess from the function.

These were WIN32 ifdeffed out when doing the initial Linux port, now properly implemented.

2021-01-05 10:55 UTC, OmniBlade requested changes

2021-01-05 10:55 UTC, OmniBlade commented on redalert/session.cpp
> +    ffd->Close();
This needs to be gated by a check against found as if it wasn't found, ffd will be null and it will crash as I discovered when I tested it.

2021-01-10 15:31 UTC, hifi commented
This can also be re-reviewed.

2021-01-11 22:35 UTC, OmniBlade approved these changes
Looks okay on windows to me now.

2021-01-12 06:58 UTC, merged