change tiberian to use the same method of save/load as redalert
TheAssemblyArmada/Vanilla-Conquer pull request #317
Opened 2020-12-29 21:21 UTC by capsterx

The vtable hacking was not working on linux64 or the nintendo switch and I was not sure how to fix it.
So I switched the tiberian code to use the Read and then placement new with NoInitClass, which seems to be working.

2020-12-29 23:30 UTC, OmniBlade requested changes
Apart from the pragma once which to remain inkeeping with the rest of the code base should be an ifdef guard, the PR needs to be formatted with our clang format. I'll need to do some further testing to try and confirm it works on windows and will probably get @hifi to check linux, but overall this makes the code more similar between the two games and removes a nasty hack so I'd like to work towards getting this merged.

2020-12-29 23:30 UTC, OmniBlade commented on common/noinit.h
> +#pragma once
We use ifdef guards in this project rather than pragma once.

2020-12-29 23:58 UTC, capsterx commented on common/noinit.h
> +#pragma once
I updated it to use header guards

2020-12-31 03:20 UTC, capsterx commented
This somehow breaks buildings displaying and sidebar and I cannot figure out where that happens, it even breaks for brand new games after a load.

2020-12-31 05:55 UTC, capsterx commented
> This somehow breaks buildings displaying and sidebar and I cannot figure out where that happens, it even breaks for brand new games after a load.

I have found part of the sidepart part, but not the building part.

2020-12-31 23:03 UTC, tomsons26 commented
This PR is scary af, ngl, but it is necessary to do as the save load system is the one of the main blockers to commonizing quite a bit of game code.

2020-12-31 23:43 UTC, capsterx commented
> > This somehow breaks buildings displaying and sidebar and I cannot figure out where that happens, it even breaks for brand new games after a load.
> 
> I have found part of the sidepart part, but not the building part.

I found the building part, it was missing a NoInit of a superclass on buildings.   It seems to be working correctly now.

2021-01-05 12:53 UTC, OmniBlade requested changes
This needs rebasing on the latest vanilla branch as noinit was moved to common in another PR already I believe. I've done some testing on msvc 64bit builds and it appears to be working fine, unless @tomsons26 or @hifi have any objections I'll be happy to merge onces the rebase is done.

2021-01-05 12:53 UTC, OmniBlade commented on redalert/function.h
> +          // Should be part of WWLIB.H. This is used in JSHELL.CPP.
Odd whitespacing here? Formatting issue?

2021-01-05 14:37 UTC, capsterx commented on redalert/function.h
> +          // Should be part of WWLIB.H. This is used in JSHELL.CPP.
Not sure, I ran clang-format over it, but I think I fixed it in the latest push

2021-01-06 04:43 UTC, hifi commented
I'm fine with this after conflicts are resolved and rebased. :+1:

2021-01-06 19:07 UTC, capsterx commented
Rebased

2021-01-06 20:11 UTC, OmniBlade approved these changes

2021-01-06 20:11 UTC, merged