Make SDL2 more configurable, common settings
TheAssemblyArmada/Vanilla-Conquer pull request #322
Opened 2020-12-31 08:51 UTC by hifi

To get the SDL2 renderer properly configurable we need to have a global and shared settings storage. OptionsClass would be ideal but because they are slightly different and use different types for adjustable variables I decided to add a new SettingsClass instead to go forward.

We can migrate from OptionsClass to SettingsClass or vice versa in the future but for now I need a way to set video options (including hw/sw cursor selection, renderer selection [sw/glsl]).

This PR adds support for setting the SDL2 renderer resolution for both windowed+fullscreen and depth. We also _default_ to what would be sane on a modern system to use the native desktop resolution fullscreen. This is debatable and could be changed back to a small window or 1280x800 window by changing the default settings in the SettingsClass constructor.

I'll add support to toggling between fullscreen and windowed once this is merged one way or another. Then having the resolutions separate makes better sense when you can toggle between custom sized window (as an example) and native display fullscreen with Alt+Enter. Aspect ratio correction/enforcing would also be an interesting option to add regardless of the resolution selected.

2020-12-31 12:20 UTC, wdigger commented on common/settings.h
> +#include "ini.h"
Including before `#ifndef XXXX` it's a strange idea, especially since this include not needed at all.
Work has already begun in #303 on getting rid of unnecessary includings, which is a very good practice.

2020-12-31 12:28 UTC, wdigger commented on common/settings.cpp
> +
Is those defaults have sense?
If those values are just a stubs, may be better to construct settings with the file, it will protects from using before proper initialisation of fields.

2020-12-31 12:32 UTC, wdigger commented on common/settings.h
> +        int Depth;
Is it possible to skip setting a custom color depth altogether? It is always best to use the one that the hardware actually uses. This will both simplify implementation and be faster.

2020-12-31 12:58 UTC, hifi commented on common/settings.h
> +#include "ini.h"
This class depends on INIClass. Are you implying I should use a class declaration here and include the real header in the cpo file?

2020-12-31 12:59 UTC, hifi commented on common/settings.h
> +        int Depth;
It's actually a setting for the SDL texture depth that's being used for displaying rather than screen depth. 

Would `TextureDepth` make more sense?

2020-12-31 13:05 UTC, hifi commented on common/settings.cpp
> +
The defaults are accounted for during video init. Fullscreen needs to have zeroes to default to desktop resolution and windowed so that if you set 480 height from other settings it will be automatically preferred.

2020-12-31 13:09 UTC, wdigger commented on common/settings.h
> +#include "ini.h"
Reference is not a class usage. You may just use `class INIClass;`

2020-12-31 13:14 UTC, wdigger commented on common/settings.h
> +        int Depth;
I saying not about naming, but about field at all. May be it make sense to determine native pixel format with `SDL_RendererInfo`

2020-12-31 13:17 UTC, wdigger commented on common/settings.h
> +        int Depth;
Here is example
```  /* Determine optimal pixel format for current window */
  SDL_RendererInfo render_info = {0, 0, 0, {0}, 0, 0};
  SDL_GetRendererInfo(renderer, &render_info);
  for (Uint32 i = 0; i < render_info.num_texture_formats; i++) {
    Uint32 format = render_info.texture_formats[i];
    int bpp = SDL_BITSPERPIXEL(format);
    if (32 == bpp) {
      pixel_format = format;
      break;
    }
  }
  SDL_PixelFormatEnumToMasks(pixel_format, &bpp,
                             &Rmask, &Gmask, &Bmask, &Amask);
```

2020-12-31 13:22 UTC, hifi commented on common/settings.h
> +        int Depth;
Agree detecting is better. I will update accordingly.

2020-12-31 13:27 UTC, hifi commented on common/settings.h
> +#include "ini.h"
Yes, that's what I meant. I'll update accordingly.

2020-12-31 20:20 UTC, hifi commented on common/settings.h
> +        int Depth;
I simplified this to getting the pixel format of the created window. If that's wrong, please explain why. Your snippet seems to be searching for a pixel format that's 32-bit rather than trying to detect what the preferred pixel format is.

2020-12-31 22:27 UTC, tomsons26 commented
Don't particularly like introducing a new class given OptionsClass is a thing, maybe we should delay this introduction while we refactor OptionsClass?

2021-01-01 06:35 UTC, hifi commented
Give me a good interim solution that isn't adding 6 globals to each game and copy pasting the ini reading/writing bits to both as well.

If it would make more sense to adjust this to look more like the OptionsClass so it's easy to merge later I'm open to that.

2021-01-05 13:03 UTC, OmniBlade requested changes

2021-01-05 13:03 UTC, OmniBlade commented on common/video_sdl2.cpp
> +    if (!Settings.Video.Windowed) {
CCHyper has fed back that native full screen has issues with alt-tab and suggests the default should be windowed fake fullscreen instead which a lot of modern games default to.

2021-01-05 13:20 UTC, OmniBlade commented
It seems to work as expected. Barraing discussing the suggested change I'm more or less happy with this. I'm not sure what the benefit of having both the window dimensions and none window dimensions are though?

2021-01-05 13:28 UTC, hifi commented on common/video_sdl2.cpp
> +    if (!Settings.Video.Windowed) {
AFAIK it works like that with the default "native" fullscreen or does it not?

2021-01-05 13:30 UTC, hifi commented
If you toggle between fullscreen and windowed it's better to have them separate as you can have a different preference. This is more apparent when alt-enter works and the window is resizable.

2021-01-05 14:00 UTC, OmniBlade commented on common/video_sdl2.cpp
> +    if (!Settings.Video.Windowed) {
If you say so? We can merge it and sort it down the line if that turns out not to be the case I suppose.

2021-01-05 14:00 UTC, OmniBlade approved these changes

2021-01-05 19:10 UTC, merged