Some fixes and uniforming
TheAssemblyArmada/Vanilla-Conquer pull request #34
Opened 2020-06-28 21:13 UTC by wdigger

2020-06-28 21:33 UTC, OmniBlade requested changes

2020-06-28 21:33 UTC, OmniBlade commented on redalert/winstub.cpp
> +#ifndef REMASTER_BUILD
This probably wants to be gated behind `#if !defined REMASTER_BUILD && !defined _DEBUG` so that it isn't enabled in release builds.

2020-06-28 21:44 UTC, OmniBlade commented on tiberiandawn/gadget.cpp
> +    if (this == StuckOn || (flags & KEYBOARD)
Original code for this looks like it abused unsigned comparison behaviour as an optimisation, changing the line to `if (this == StuckOn || (flags & KEYBOARD) || (flags && (unsigned)(mousex - X) < (unsigned)Width && (unsigned)(mousey - Y) < (unsigned)Height)) {` will fix the behaviour with fewer comparisons and keep the apparently intended behaviour, though it keeps the code less clear on exactly what the check is.

2020-06-28 21:49 UTC, wdigger commented on redalert/winstub.cpp
> +#ifndef REMASTER_BUILD
Good idea!

2020-06-28 21:56 UTC, wdigger commented on tiberiandawn/gadget.cpp
> +    if (this == StuckOn || (flags & KEYBOARD)
Will do.

2020-06-29 11:34 UTC, hifi requested changes
Additionally to the comments provided I would prefer we restrain from adding more winapi code as we're going to go portable soon.

EDIT: You could also split out the debug output stuff from this PR so we can merge the other changes.

2020-06-29 11:34 UTC, hifi commented on redalert/winstub.cpp
> +        CloseHandle(DebugFile);
I don't like the output file is opened and closed per every print call.

2020-06-29 11:34 UTC, hifi commented on redalert/winstub.cpp
> +    } else {
This depends on the side effect of `CloseHandle` not resetting the file handle. It's not very clear how this function works.

2020-06-29 11:34 UTC, hifi commented on redalert/dllinterface.cpp
> +void GlyphX_Debug_Print(const char* debug_text, ...)
Remaster is not a second class citizen (yet). Both implementations should use the format string and build the complete output.

I suggest making `WWDebugString` call `GlyphX_Debug_Print` with the final string instead.

2020-06-29 16:15 UTC, wdigger commented on redalert/winstub.cpp
> +        CloseHandle(DebugFile);
Are we really want to change original code?
Where is boundaries of improvements?

2020-06-29 16:55 UTC, hifi commented on redalert/winstub.cpp
> +        CloseHandle(DebugFile);
Vanilla is not a source code restoration project but it aims to be clean and portable while preserving gameplay. Ideally a lot of the code between TD and RA are merged into common and they have only very game specific code in their own directories.

We want this to be portable with the SDL2 library to Linux, macOS and beyond so anything Windows specific needs to be rewritten one way or the other.

2020-06-29 17:16 UTC, wdigger commented on redalert/winstub.cpp
> +    } else {
I'm removed logging related changes from MR for now.

2020-06-29 18:27 UTC, hifi approved these changes
Tested with Remaster and Vanilla, both seemed to still work as far as I remember.

2020-06-29 21:08 UTC, OmniBlade approved these changes

2020-06-29 21:12 UTC, merged