[TD/RA] Move some files to common library
TheAssemblyArmada/Vanilla-Conquer pull request #37
Opened 2020-06-30 01:26 UTC by wdigger

2020-06-30 04:43 UTC, hifi commented
Nice work :ok_hand:

2020-06-30 08:47 UTC, OmniBlade requested changes

2020-06-30 08:47 UTC, OmniBlade commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
With the inclusion of gbuffer and ddraw, you will need to built common twice, once as common with REMASTER_BUILD set without linking to the ddraw libs and once without it set, so just have it build commonv from the sources as well and link all the libraries just for that one.

2020-06-30 09:51 UTC, wdigger commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
I removed SetVideoMode calls from RE.
DDraw not linking with dlls anymore, at least in release.

2020-06-30 13:08 UTC, OmniBlade commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
I think for future proofing its probably a good idea to separate the vanilla and remaster builds of common completely so we have more freedom to add code the differs between remasters and standalone builds. Something like the following:

```CMake
file(GLOB_RECURSE COMMON_HEADERS "common/*.h")

if(BUILD_REMASTERTD OR BUILD_REMASTERRA) 
    add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
    target_link_libraries(common PUBLIC winmm)
    target_compile_definitions(common PUBLIC REMASTER_BUILD)
endif()

if(BUILD_VANILLATD OR BUILD_VANILLARA)
    add_library(commonv STATIC
        ${COMMON_SRC}
        ${COMMON_HEADERS}
        common/soundio.cpp
    )

    target_link_libraries(commonv PUBLIC ddraw dxguid dsound winmm)
endif()
```

2020-06-30 16:21 UTC, wdigger commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
I believe that renaster not really interested in video, sound and input, it is possible we can separate logic at all. Future will tell.

2020-06-30 16:33 UTC, wdigger commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
Other war - extract interface for vide/sound/input and make different realizations for different cases.
video_ddraw.lib
video_sdl.lib
video_dummy.lib
and so on...

2020-07-01 07:48 UTC, OmniBlade commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
Can you move ddraw and dxguid as link libraries to commonv only then so we remove the risk of accidentally linking against them when we don't intend to? We can look at creating separate implementations for video and other platform specific bits as we work on porting the game to another framework.

2020-07-01 08:16 UTC, wdigger commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
Nop, right now ddraw uses in many places across all the library code. I believe this big work is not in scope of this PR.

2020-07-01 11:53 UTC, hifi commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
I don't think the remaster code needs to link ddraw, it only uses headers and data types.

2020-07-01 12:12 UTC, wdigger commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
Remaster release don't linked with ddraw.

2020-07-01 13:14 UTC, OmniBlade commented on CMakeLists.txt
> +add_library(common STATIC ${COMMON_SRC} ${COMMON_HEADERS})
Which is why common shouldn't be linking it either, so there is no chance of accidentally pulling it in by calling something in remaster code down the line unintentionally.

2020-07-01 22:42 UTC, OmniBlade approved these changes

2020-07-02 03:11 UTC, merged