[TD/RA] Restored save/load UI, fixed some crashes
TheAssemblyArmada/Vanilla-Conquer pull request #38
Opened 2020-07-02 08:01 UTC by wdigger

One question here - what C++ standard we are based on?
In this PR I use windows specific file system functions, it is possible to use C++ 17 filesystem functionality but this standard is "too innovative" for some platforms.

2020-07-02 08:34 UTC, hifi commented
Ideally we should avoid adding any new Windows specific code and use standards implementations where possible.

If you can make C++17 pass the CI's MinGW gcc 7.3  compiler I'd say go for it and we adopt it as the target standard. Adding `-std=c++17` to the MinGW build flags may be a good thing to do in this PR.

2020-07-02 08:41 UTC, wdigger commented
Ok, will try to enable 17.

2020-07-02 09:01 UTC, hifi commented
I discussed with @OmniBlade and he instead suggested we stick with C++11 and use POSIX emulation of Windows where it exists and do custom emulation where it doesn't.

I didn't really think through how much it hurts with portability to use a new standard like C++17 where it serves only little purpose.

Sorry for the confusion.

2020-07-02 13:28 UTC, OmniBlade requested changes

2020-07-02 13:28 UTC, OmniBlade commented on common/file_helpers.cpp
> +    HANDLE rc = FindFirstFileA("SAVEGAME.*", &ff);
The dirent implementation doesn't match the win32 api as it doesn't appear to filter based on the filename in the same way, probably need to use fnmatch. Also, might want to make the function take a filename filter rather than hard coding it as there are other instances in the code where a list of files needs to be enumerated such as the mix loading code that looks for SC*.MIX and SS*.MIX.

2020-07-02 13:51 UTC, wdigger commented on common/file_helpers.cpp
> +    HANDLE rc = FindFirstFileA("SAVEGAME.*", &ff);
I'm not finished yet.. ;)

2020-07-02 16:05 UTC, wdigger commented on common/file_helpers.cpp
> +    HANDLE rc = FindFirstFileA("SAVEGAME.*", &ff);
Unfortunately mingw don't fully posix compatible, fnmatch not supported, because of this I switch mingw version to win32 functions.

2020-07-02 20:55 UTC, OmniBlade commented
One more thing I should probably mention is the for now, we are trying to stick to how the original code base did things, so it would be the DynamicVectorClass and normal C strings instead of the C++ standard library stuff. I need to write a developers guide at some point to document this so we don't spring it on developers such as yourself in the middle of writing some code.

2020-07-02 22:43 UTC, wdigger commented
And why then do you need C ++ 11 or even more so 17?
It’s just silly to switch to a new standard, but use it in the paradigm of 20 years ago. Will Tesla refuel with diesel?

2020-07-03 08:45 UTC, OmniBlade commented
For standalone you are right, we wouldn't need C++11 even really, though I believe a few bits are used in the dll interface code. The game code is written in the old paradigm though and I don't think we want to stray too much from that flavour at this stage of the project. There might be an argument to heavily refactor it down the road, but I think we should tack closely to how the original code was written until we have everything working correctly.

2020-07-03 09:24 UTC, hifi commented
We also need to remember Petroglyph is probably using C++11 or C++17 and if we keep backporting their updates we also can't go back to the 90's unless we always rewrite incompatible code.

A hybrid model is probably the best route _for now_ what @OmniBlade suggested to keep using the same style and classes the original code did where possible.

We will write down some guidelines how to manage this situation. As for now, safest bet is to keep the code close to original style.

2020-07-03 10:58 UTC, wdigger commented
You have contradicted positions, @OmniBlade wants to restore code "as is" (CD with DOS disk letters, for example) but @hifi wants to make code crossplatform. So you go in different directions and if someone wants to go with you, then he gets into an uncertain situation.
About concrete case - existing (WW?) vector realisation is terrible and totally unsafe, using it in newly writing code is a risky trick.
I totally agree with not changing existing code without critical need, but in this situation we speaking about newly written code. Is it make sense to use historical artefacts for crossplatform abstractions and other newly creating stuff?

2020-07-06 09:24 UTC, OmniBlade commented on tiberiandawn/vector.h
> +#include <cstdlib>
Watch out for this, not all C++ libs define the functions in the global namespace from the C++ versions of these headers, them being only in the `std::` namespace instead, so as it is, this could cause portability issues without additional `using` directives.

2020-07-06 09:59 UTC, wdigger commented on tiberiandawn/vector.h
> +#include <cstdlib>
Is it possible in more detail? What kind of compiler is it that interprets the standard so freely?

2020-07-06 10:37 UTC, OmniBlade commented on tiberiandawn/vector.h
> +#include <cstdlib>
Standard only requires that the C++ headers provide the functions in the `std::` namespace and recent version of libstdc++ on linux at least appear to do just that. Standard also requires that the normal C headers exist and provide them in the global namespace, so you can continue to use those headers if you want the global names or you can add using directives after including the C++ versions for the same effect. There is nothing in the standard saying the C++ headers can't continue to provide the global namespace versions as well, which is what the windows SDK does, but you can't rely on it unfortunately.

2020-07-06 12:51 UTC, wdigger commented on tiberiandawn/vector.h
> +#include <cstdlib>
C++ 11 have no "XXXX.h" headers at all, content and namespace placing defined in .h files are not specified.
The fact that C calls are present in the global namespace when using <cxxx> headers is no less a non-standard extension than using <xxxxx.h> headers.
I will change this back for your peace of mind, but the code with this will not get better or more standard, unfortunately.

2020-07-06 14:05 UTC, OmniBlade commented on tiberiandawn/vector.h
> +#include <cstdlib>
the xxxx.h headers are marked as deprecated but are currently required to be supplied by the C++11 standard and are unlikely to be removed in future standard revisions. However I do support moving to the cxxxx headers instead provided the C library calls are updated with the `std::` prefix or `using` directives are added to ensure that the code compiles withe C++ libraries that don't expose the functions in the global namespace from the cxxxx headers.

2020-07-06 14:33 UTC, tomsons26 commented
I'd recommend looking at how SoundControlsClass handles dialog positioning and using the #if(0) case here to write code similar to SCC. There's no reason to keep this dialog to a fixed position any further.

2020-07-07 17:31 UTC, wdigger commented
No chance.

2020-07-07 17:31 UTC, closed without merging