Mousewheel sidebar scrolling
TheAssemblyArmada/Vanilla-Conquer pull request #383
Opened 2021-01-08 19:45 UTC by mvdhout1992

Implements handling of mousewheel scroll bar up and down SDL events and add sidebar scrolling code

2021-01-08 19:54 UTC, hifi requested changes
Some copypasta issues but otherwise looks okay. And please add TD support in the same PR so they keep feature parity.

Also these changes are small enough to fit a single commit even when hooking up both games. Cleanup commits should be squashed away anyway so that's something that needs to be done regardless of how the commits are laid out.

2021-01-08 19:54 UTC, hifi commented on common/settings.cpp
> +    Options.MouseWheelScrolling = ini.Get_Bool("Options", "MouseWheelScrolling", Video.FrameLimit);
Default value is wrong.

2021-01-08 19:54 UTC, hifi commented on common/settings.cpp
> +    ini.Put_Bool("Options", "MouseWheelScrolling", Video.FrameLimit);
Writes the wrong value to ini.

2021-01-09 08:43 UTC, mvdhout1992 commented on common/settings.cpp
> +    ini.Put_Bool("Options", "MouseWheelScrolling", Video.FrameLimit);
Will fix the INI writing.

2021-01-09 08:44 UTC, mvdhout1992 commented on common/settings.cpp
> +    ini.Put_Bool("Options", "MouseWheelScrolling", Video.FrameLimit);
Ok I'll add TD support too and fix the ini copypasta.

2021-12-09 11:38 UTC, OmniBlade commented
Superceded by cleaned up version #710.

2021-12-09 11:38 UTC, closed without merging