Disable blinking airfields for non-remaster builds. Blinking airfields are a change which Petroglpyh added to remaster
TheAssemblyArmada/Vanilla-Conquer pull request #386
Opened 2021-01-08 21:07 UTC by mvdhout1992

Disable blinking airfields for non-remaster builds. Blinking airfields are a change which Petroglpyh added to remaster

2021-01-09 06:06 UTC, hifi requested changes

2021-01-09 06:06 UTC, hifi commented on redalert/bdata.cpp
> +                  {STRUCT_TESLA, BSTATE_ACTIVE, 0, 10, 2}};
Better to just move the closing brace on its own line and ignore that the formatting is a bit wonky so you don't need to copy the STRUCT_TESLA line over.

2021-01-09 08:30 UTC, mvdhout1992 commented on redalert/bdata.cpp
> +                  {STRUCT_TESLA, BSTATE_ACTIVE, 0, 10, 2}};
Will update and do just that. Yeah I initially wanted to do the brace on a newline but went with this cause it looks less wonky. Will do it on a newline instead.

2021-01-14 00:39 UTC, tomsons26 commented
Yeah afaik this is the only change, that entry isn't in 3.03.

2021-01-15 19:45 UTC, tomsons26 approved these changes

2021-02-16 05:12 UTC, hifi commented
Just clean up the ifdef block so you don't need to repeat the closing `};` and I'll merge this.

2021-07-03 05:25 UTC, hifi approved these changes

2021-07-03 05:29 UTC, merged