Visual Controls
TheAssemblyArmada/Vanilla-Conquer pull request #42
Opened 2020-07-06 16:35 UTC by tomsons26

Convert functions in TD are very much the same as RA's but range is different.
Divide_With_Round based on ASM in retail binary.

2020-07-06 21:53 UTC, OmniBlade commented on tiberiandawn/options.cpp
> -#if (0)
Stuff that is disabled for the remaster should be surrounded with `#ifndef REMASTER_BUILD` to prevent it being included in the remaster dll. Is this intentionally enabled for the remasters as well?

2020-07-07 08:02 UTC, OmniBlade approved these changes
Works correctly for me in standalone.

2020-07-08 05:03 UTC, hifi requested changes

2020-07-08 05:03 UTC, hifi commented on CMakeLists.txt
> +    common/lib.cpp
Since these functions are only used in TD I would prefer the header definitions are moved back to TD and lib.cpp as well. Also because they are used only once in OptionsClass they could be just dumped as inline static in options.cpp in my opinion.

@OmniBlade your thoughts?

2020-07-08 08:19 UTC, OmniBlade commented on CMakeLists.txt
> +    common/lib.cpp
Indeed, makes sense for them to stay in TD, possible candidate for unification down the road, but there is plenty of other lower hanging fruit than that yet.

2020-07-09 18:25 UTC, hifi approved these changes
Yeah, this cool. You just need to rebase it.

2020-07-10 22:19 UTC, merged