Remove use of UINT16_MAX
TheAssemblyArmada/Vanilla-Conquer pull request #482
Opened 2021-01-18 16:22 UTC by ccawley2011

When building as C++ for RISC OS, UnixLib only defines `UINT16_MAX` when `__STDC_LIMIT_MACROS` is defined, an issue inherited from older versions of glibc. I've submitted a patch to fix this in UnixLib, but since `UINT16_MAX` is only used once, it makes sense to remove it here as well.

http://www.riscos.info/pipermail/gcc/2021-January/007081.html
https://sourceware.org/bugzilla/show_bug.cgi?id=15366

2021-01-19 10:33 UTC, OmniBlade requested changes

2021-01-19 10:33 UTC, OmniBlade commented on common/wwkeyboard.h
> +    uint8_t DownState[0x2000];
I don't mind removing the use of the macro if it helps portability, but can you add a comment for the maths as it originally was so anyone reading the code knows where the magic number came from?

2021-01-21 13:30 UTC, ccawley2011 commented on common/wwkeyboard.h
> +    uint8_t DownState[0x2000];
OK, done.

2021-01-21 13:47 UTC, OmniBlade approved these changes

2021-01-21 13:48 UTC, merged