Do not crash if critical file is not found
TheAssemblyArmada/Vanilla-Conquer pull request #504
Opened 2021-01-29 03:26 UTC by giulianobelinassi

I am opening a new PR because the previous was automatically closed when I was cleaning my main branch.

If a critical file (such as temperat.pal) is not found in the MIX
files, the game crashes. This commit fixes this by checking if
opened file is not NULL.

The original crash reason was because an incorrect version of Is_Open
was being called. This was fixed by explicit calling the correct
function.

We also change DBG_FATAL_COMMON to call ShowSimpleMessageBox.

Closes #486

2021-01-29 03:34 UTC, giulianobelinassi commented
Looks like Windows is not finding the SDL headers and shared libraries. Is everything OK on the CI side?

2021-01-29 07:24 UTC, hifi commented
There are a few things that need to be done.

First is you need to move all SDL2 related code into `debugstring.cpp`. Wrap all that within `#ifdef SDL2_BUILD`. This keeps the header interface generic and whoever includes it and calls the functions don't need to know that SDL2 is being invoked even though it's implied in SDL2 builds.

Second `debugstring.cpp` needs to be moved within `common/CMakeLists.txt` to `COMMONR_SRC` and `COMMONV_SRC` so that the SDL2 build flag is being set properly and they get the different behavior. Remaster dlls don't link with SDL2 but they also need the debug print code.

Also I'm still not fully convinced the fix is correct. Glancing over once more it seems `BufferIOFileClass::Open` unconditionally returns true even if `RawFileClass::Open` fails but that's only one part of the mess that's happening. For this crash to happen the overridden `Is_Open()` needs to return true in `RawFileClass::Raw_Seek` when the raw file is not in fact open.

Though if the fix is indeed correct we need to make sure RawFileClass only calls its own members all the time and not just at a few places as that makes it inconsistent. Even the original code does have some of the calls prefixed with RawFileClass but not all.

2021-02-02 23:37 UTC, giulianobelinassi commented
Done. Wrapped the SDL_SimpleMessageBox in a function inside debugmessage.h, and also implemented messagebox using winuser.h MessageBoxA, if available.

As for if the being correct, it solves the testcase which opened this PR. I did explicitly called the class own members, but I am still not sure if I covered everything. 

Do you want me to squash all these commits into a single one and open a new PR?

2021-02-07 06:41 UTC, hifi commented on common/CMakeLists.txt
> -endif()
Just a slight annoyance that your editor forced a line ending. You can configure editors like Vim not to do that.

2021-02-07 06:41 UTC, hifi commented on common/debugstring.cpp
> +    /* Prefer WinAPI MessageBoxA on Windows.  */
Why, though? There's really no need to do that.

2021-02-07 06:42 UTC, hifi commented on common/debugstring.cpp
> +    vsnprintf(buffer, 256, fmt, args);
Use `sizeof`, never assume the size.

2021-02-07 06:58 UTC, hifi requested changes
I accidentally used the single comment button a few times. Only minor comments anymore.

You can squash the commits within a PR by force pushing to your branch.

I still want an opinion from @OmniBlade what we should do with the file classes. The functions are virtual for a reason but it all falls apart and we need to be careful not to botch it further.

Anyway good work, sorry for being unresponsive for a while.

2021-02-07 06:58 UTC, hifi commented on common/debugstring.h
> +#define _DBG_FATAL_COMMON(x, ...)                                                                                      \
I don't really see the point of this, just add the call to FatalErrorMessageBox directly to DBG_FATAL after calling Debug_String_Log? You also can't assume you can print to stdout directly, use the log function.

2021-02-07 06:58 UTC, hifi commented on common/rawfile.cpp
> +    const char* errorstr = strerror(error);
No reason to use local variables, just pass them as arguments.

2021-02-07 06:58 UTC, hifi commented on common/rawfile.cpp
> +    printf(fmtstring, filename, errorstr);
Use DBG_ERROR instead of printf.

2021-02-07 06:58 UTC, hifi commented on common/rawfile.cpp
> -        /*
I don't think this needs to be moved when the error handling works as intended.

2021-07-03 12:18 UTC, hifi commented
Will you continue this PR?

2021-07-03 20:53 UTC, giulianobelinassi commented
> Will you continue this PR?

Not for a while. If someone wants to continue it, fell free.

2021-08-05 22:24 UTC, OmniBlade commented
It seems that the issue with Error being called was added during the refactor for case insensitivity. The original code has the function as an empty place holder that did not exit on error. Perhaps worth removing the fatal aspect of the function and change it to just log the error instead?

2022-01-11 11:46 UTC, OmniBlade commented
Supercded by #735

2022-01-11 11:46 UTC, closed without merging