Platform dependent video incapsulation proposal
TheAssemblyArmada/Vanilla-Conquer pull request #51
Opened 2020-07-08 21:06 UTC by wdigger

Main idea - encapsulate platform (framework) dependent code in separated library.
Next step - to do the same with audio, input and event circle.
Like a proof of concept I plan to use SDL2 as backend.

2020-07-09 04:02 UTC, hifi commented
I have no issues with this approach. Just try to keep the commits small and incremental where possible.

2020-07-09 07:16 UTC, wdigger commented
Unfortunately, right now project contains too much unnecessary includes, even small change in header may be a casualty of massive changes in whole project. I believe we will cleanup headers in some point.

2020-07-19 05:41 UTC, hifi commented
I'm really interested in getting this merged so that the remaster build would be ddraw free as gbuffer is one of the biggest obstacles in getting things to compile on Linux at all (many files depend on the header).

2020-07-22 06:12 UTC, hifi requested changes
RA crashes for me before it gets to main menu with null video. It shouldn't draw anything for sure but it shouldn't crash either. I couldn't get a good stack trace from winedbg.

Otherwise I think these changes are good as without ddraw the ddraw.h header is not required to build and remaster seems to work fine.

2020-07-22 14:24 UTC, wdigger commented
RA crash fixed

2020-07-23 05:53 UTC, hifi requested changes

2020-07-23 05:53 UTC, hifi commented on common/video_null.cpp
> +    return false;
This should be true as the null video driver should "work".

Setting it to true still crashes RA. The game should run without rendering.

2020-07-23 12:18 UTC, wdigger commented on common/video_null.cpp
> +    return false;
Done. But, without graphics, it's not clear what application actually do. At least no crashes.

2020-07-23 14:36 UTC, hifi approved these changes
Tested all combinations and all seemed to work just fine with ddraw and null video. I could even navigate into the game from the menu with the keyboard with dsound enabled so I knew the game was running.

Excellent work, thanks!

2020-07-23 14:36 UTC, merged