Changes default interpolation from scanline to full linear.
TheAssemblyArmada/Vanilla-Conquer pull request #539
Opened 2021-02-08 23:36 UTC by OmniBlade

Appearance on scaled resolutions that are not integer scaled is much improved.

2021-02-09 06:02 UTC, hifi commented
Can you make this an option in SettingsClass and set the default to full linear? Maybe in the Video section?

2021-02-09 23:11 UTC, OmniBlade commented
Yes I can.

2021-02-11 05:34 UTC, hifi requested changes
Tested the modes work as intended with a few cleanups required.

2021-02-11 05:34 UTC, hifi commented on redalert/mapsel.cpp
> +    Settings.Video.InterpolationMode = 1;
Remove this assignment and use `1` in the call. Setting it will change the ini value to `1` after you quit the game.

2021-02-11 05:34 UTC, hifi commented on redalert/score.cpp
> -    CopyType = 1;
You can either revert these changes because they are ifdeffed out or fix them to use the argument as well.

2021-02-12 10:53 UTC, hifi approved these changes

2021-02-14 13:07 UTC, merged