Fix monster tank mission (Remaster bug)
TheAssemblyArmada/Vanilla-Conquer pull request #575
Opened 2021-02-16 15:06 UTC by mvdhout1992

This fixes the Monster Tank Madness Aftermath mission not working correctly in VanillaRA. The issue is that a group of Soviet soldiers which are supposed to get killed by the Monster Tanks walk into your base instead and destroy your Weapons Factory too soon for you to respond because your base isn't discovered by you yet. The Monster Tanks don't attack these soldiers because the player has not unshrouded the Monster Tanks causing the threat code to not consider anything the Monster Tanks try to attack a threat. In 3.03 there's special single player logic to unshroud a very small part of the map if an enemy unit is firing from shroud, the remaster doesn't have this logic.

The Remaster changed the map reveal code but they forgot to port some special logic for single player. Works like this:

a single player check for revealing a small part of the shroud for the human player in single player even if the target is not a object (I think when its an overlay)

in multiplayer it checks if the target is an object

whats happening is that it reveals the monster tanks a bit on mission start after they start firing either the ground or overlays or something

which causes them to be discovered, which makes sure the threat code works correctly and the monster tanks and the soviet players will attack each other (the code looks at whether the human player has discovered the monster tanks

and that causes the riflemen to get kiled by monster tanks instead of moving into your base and killing wf

2021-03-18 16:05 UTC, OmniBlade requested changes

2021-03-18 16:05 UTC, OmniBlade commented on redalert/techno.cpp
> +        // If a projectile was fired from a unit that is hidden in the darkness,
Probably worth inverting this so it checks game mode first so the other checks aren't done needlessly now that the MP logic isn't part of the if block.

2021-07-27 16:12 UTC, mvdhout1992 commented
@Nyerguds said this also affects C&C1, don't know how to test the fix in C&C1 though.

2021-11-18 13:06 UTC, OmniBlade commented
Fixes #572

2021-11-18 23:10 UTC, OmniBlade commented
Updated and extended to fix same bug in TD in PR #703

2021-11-18 23:10 UTC, closed without merging