Make DirectSound optional
TheAssemblyArmada/Vanilla-Conquer pull request #61
Opened 2020-07-15 17:39 UTC by hifi

2020-07-15 19:05 UTC, wdigger commented on common/soundio_null.cpp
> +#ifndef DSOUND
Whole file under ifdef? May be better to enable/disable on configure time?

2020-07-15 21:21 UTC, OmniBlade requested changes

2020-07-15 21:21 UTC, OmniBlade commented on CMakeLists.txt
> +    set(VANILLA_DEFS ${VANILLA_DEFS} DSOUND)
I agree with @wdigger a better approach is to add the source files to a list, then conditionally add either soundio.cpp or soundio_null.cpp with a list append directive. That way no define needed and only one cpp will get included in the final build, the one with the implementation you want. Otherwise we could end up with several defines for different audio backends being tested in the cpp files.

2020-07-16 08:31 UTC, hifi commented on common/soundio_null.cpp
> +#ifndef DSOUND
Addressed.

2020-07-16 08:32 UTC, hifi commented on CMakeLists.txt
> +    set(VANILLA_DEFS ${VANILLA_DEFS} DSOUND)
I didn't use a list per se but now it works like that.

2020-07-16 09:12 UTC, OmniBlade reviewed
Once I've given this some testing I'll be happy to approve, just one suggestion for your consideration though.

2020-07-16 09:12 UTC, OmniBlade commented on CMakeLists.txt
> +    set(COMMONV_SRC ${COMMONV_SRC} common/soundio_null.cpp)
Not a deal breaker as this syntax is valid, but more modern syntax for this is to do `list(APPEND COMMONV_SRC common/soundio_null.cpp)`

2020-07-16 13:46 UTC, OmniBlade requested changes

2020-07-16 13:46 UTC, OmniBlade commented on CMakeLists.txt
> +    set(COMMONV_SRC ${COMMONV_SRC} common/soundio.cpp)
Looks like you got the files to build the wrong way around, enabling DSOUND gets me null and disabling it gets me DSOUND with linker issues.

2020-07-16 16:32 UTC, hifi commented on CMakeLists.txt
> +    set(COMMONV_SRC ${COMMONV_SRC} common/soundio.cpp)
Should be fixed now.

2020-07-16 16:32 UTC, hifi commented on CMakeLists.txt
> +    set(COMMONV_SRC ${COMMONV_SRC} common/soundio_null.cpp)
Fixed in latest.

2020-07-20 22:15 UTC, OmniBlade approved these changes

2020-07-21 06:57 UTC, merged