Gamepad support
TheAssemblyArmada/Vanilla-Conquer pull request #627
Opened 2021-04-28 20:52 UTC by Northfear

Gamepad support from PS Vita port. Tested on Linux with Xbox Series X (or whatever that name is) controller.
I used bindings from Vita port:
Left analog stick - Cursor movement
Right analog stick - Map scrolling
Right trigger - Cursor speedup
A - Left mouse button
B - Right mouse button
X - G (Guard Area)
Y - F (Formation. RA only)
D-Pad Up/Right/Down/Left - 1/2/3/4 button
R1 - Alt (force move)
L1 - Ctrl (force attack)
SELECT - Esc (opens menu, skips videos)
START - Enter (to submit score after the mission)

2021-07-30 22:00 UTC, OmniBlade commented
Aplogies that I've only just tested this branch, I can confirm that it works on windows with an xbox360 controller as described. However there are a few issues:

First is that the mouse cursor does not move on menus when driven by a mouse.

Second is that in game if you have moved the cursor with the control pad, the mouse will also move it, but act as if it has been clicked and dragged from the last spot the control pad had moved it to.

2021-07-31 08:29 UTC, Northfear commented
That's weird. I guess I'll have to test it on Windows, since I've only tried on Linux so far.

2021-08-05 22:08 UTC, OmniBlade requested changes
The behaviour when mouse/keyboard are used along side a controller is much improved. However I do still get an odd issue where after using the control pad, the mouse cannot move over certain areas of the screen (this affects the first GDI mission prior to the sidebar being activated). Again this is window mode with RawInput=no set for the mouse.

In addition, the mouse fails to function at all in menus when the ControllerEnabled is set to true.

2021-08-05 22:08 UTC, OmniBlade commented on common/wwkeyboard.cpp
> +        if (EmulatedPointerPosX < 0)
Could you use braces even for single line ifs. I realise we don't have a style guide mandating this as of yet but we prefer it to avoid certain classes of refactoring bugs that are easier without braces.

2021-10-09 12:31 UTC, Northfear commented
@OmniBlade I've finally had some time to check it out and I think that I was able to fix windowed behavior. Also did some cleanup

2021-10-11 22:26 UTC, OmniBlade commented
@Northfear Thanks, I'll look it over as soon as I can. Can I ask if you are able to rebase your commits to remove the merge commits that have been introduced as we are trying to keep a linear history on our main branch. Also, it looks like the work you've done rearranging the input code has led to some of our CI tests needing dummy functions adding to satisfy linking.

2021-10-12 08:05 UTC, Northfear commented
@OmniBlade controller support has to be initialized in SDL first and controller itself has to be opened/closed. I haven't found a good place for it in `WWKeyboardClass`, but it fits well in `video_sdl2`.
Is there a more cleaner way of doing it maybe?

2021-10-31 21:12 UTC, Northfear commented
@OmniBlade rebased and fixed tests

2021-11-02 11:53 UTC, OmniBlade commented
Looks like the CI failures are due to formatting check not passing and `pow` symbol not being found for mingw... missing header include?

2021-11-02 15:51 UTC, OmniBlade commented
I still see error LNK2001: unresolved external symbol "class WWKeyboardClass * Keyboard" on the CI for MSVC building the test as well.

2021-11-02 17:19 UTC, Northfear commented
@OmniBlade formatting is fixed. Hopefully msvc tests are too

2021-11-02 20:42 UTC, OmniBlade commented
Okay, I believe the latest fails is because you need `#define SDL_MAIN_HANDLED` before `#include <SDL.h>` in headers as they get included before the SDL include in startup.cpp.

2021-11-03 11:21 UTC, Northfear commented
@OmniBlade replaced double with float to avoid some conversion warnings and added that define. Let's give it a go one more time I guess

2021-11-13 14:37 UTC, OmniBlade requested changes
Looks like its all working, only a few minor things really and I like one of the other maintainers to confirm it working on linux for them if possible, but seems fine on windows now.

2021-11-13 14:37 UTC, OmniBlade commented on common/wwkeyboard.cpp
> +    if (directionX == SDIR_E && directionY == SDIR_N)
Can you update this with braces even though they are one line statements as its our preferred style for new code.

2021-11-13 14:37 UTC, OmniBlade commented on common/wwkeyboard.h
> +    const float CONTROLLER_SPEED_MOD = 2000000.0f;
Could use static constexpr here?

2021-11-19 10:15 UTC, OmniBlade approved these changes

2021-11-19 11:17 UTC, merged