Add 320x200 support for VanillaTD
TheAssemblyArmada/Vanilla-Conquer pull request #647
Opened 2021-06-30 22:57 UTC by giulianobelinassi

This PR adds support to 320x200 resolution to vanillatd, the same used on MS-DOS version.

![Screenshot from 2021-06-30 13-13-15](https://user-images.githubusercontent.com/7212952/124041470-44c9ae80-d9dd-11eb-89bf-d17c64cf4889.png)

For this to work properly, DOS version of LOCAL.MIX, GENERAL.MIX and CONQUER.MIX is necessary to load the DOS version assets. The High resolution version still works if none of those files are provided.

2021-06-30 23:28 UTC, giulianobelinassi commented
I don't have remaster to check the issue and I can only rely on preprocessed sources in this case to find the bug, which is not very helpful. Can someone check why is it failing?

2021-07-01 08:03 UTC, OmniBlade commented
`error C2065: 'cfile': undeclared identifier`, so you are probably declaring cfile in a part of the ifdef block that excludes the remaster build, but then using it outside that ifdef block.

2021-07-01 12:11 UTC, tore29 commented
Brilliant stuff

2021-07-01 16:13 UTC, mvdhout1992 commented
Very impressive.

2021-07-01 16:32 UTC, giulianobelinassi commented
Finally fixed the remater issue, and the CI approved the commit on my side. I don't know what happened 

![Screenshot from 2021-07-01 13-32-28](https://user-images.githubusercontent.com/7212952/124158871-d6363080-da70-11eb-910e-2f2bb8c5bda1.png)

2021-07-02 06:55 UTC, hifi commented
I got the demo barely working with this PR to give a quick test.

The Width and Height section of Video are reserved for fullscreen output resolution. You should use a boolean conquer.ini variable to toggle between hires/lores (default to hires) as we don't yet have proper resolution adjustment in either of the games so they adjust to anything. This allows the user to use the scaler to scale either hires or lores to their liking in both fullscreen and windowed.

Also some English text is overflowing the buttons but that may be that I have incorrect fonts in the demo version. Also while building structures or units and hovering over a cameo the tooltip text flickers or shows up empty, again could be data related.

Regardless, with the video stuff resolved and code review done I would like this to be merged and work be continued in smaller PRs to adjust things where needed.

Great work!

2021-07-02 14:15 UTC, giulianobelinassi commented
> I got the demo barely working with this PR to give a quick test.
> 
> The Width and Height section of Video are reserved for fullscreen output resolution. You should use a boolean conquer.ini variable to toggle between hires/lores (default to hires) as we don't yet have proper resolution adjustment in either of the games so they adjust to anything. This allows the user to use the scaler to scale either hires or lores to their liking in both fullscreen and windowed.

By fullscreen output resolution, you mean the fullscreen resolution that SDL (or ddraw) will draw to? because if so, it seems broken because it always output to 1080p on my side. But that could be an issue with SDL on Wayland as well.

> 
> Also some English text is overflowing the buttons but that may be that I have incorrect fonts in the demo version. Also while building structures or units and hovering over a cameo the tooltip text flickers or shows up empty, again could be data related.
> 

The tooltip works fine on my side, although it render German text for me for some reason. There is some font spacing issue, yes, just compare the REPAIR button with the original DOS version. Also, the scorescreen shows no text at all, but these are issues for future fix.

There are also issues to how clickmaps are registered in this branch. The code always upscale the click coordinates to 2x, which  makes impossible to select GDI Mission 2. I fixed this in on another branch and I will submit another PR when this have been merged.

> Regardless, with the video stuff resolved and code review done I would like this to be merged and work be continued in smaller PRs to adjust things where needed.
> 
> Great work!

Thank you :)

2021-07-03 05:39 UTC, hifi commented
> By fullscreen output resolution, you mean the fullscreen resolution that SDL (or ddraw) will draw to? because if so, it seems broken because it always output to 1080p on my side. But that could be an issue with SDL on Wayland as well.

Yes, it should default to "desktop fullscreen" when the width and height are zero. Probably a wayland issue if SDL2 can't select fullscreen resolutions. You could test with Xorg to see the correct behavior happens.

2021-07-03 21:23 UTC, giulianobelinassi commented
Done. Added a new "HighResolution" boolean option in CONQUER.INI.

2021-07-03 22:01 UTC, tore29 commented
I got to test this a little bit. Good work, but there are a few points.

- The sidebar portaits do not remap according to the colours of your faction and stay GDI gold. When playing Nod military vehicles should be remapped to gray and utility vehicles (MCV and harvester) should be remapped to red. This also applies to multiplayer colours.
- There are a few alignment problems here and there. The unit and building portaits are a bit too large so they overflow certain things on the sidebar. If they were one pixel smaller from top and bottom I believe it would fix most of this.
- The covert ops entries are so close they overlap each other
- Missing "placeholder portaits when" (grey slabs) there are not enough units and buildings to fill the sidebar 
- Campaign menu selects only GDI for some reason. Clicking on the Nod logo starts the GDI campaign.

2021-07-03 23:16 UTC, giulianobelinassi commented
> I got to test this a little bit. Good work, but there are a few points.
> 
>     * The sidebar portaits do not remap according to the colours of your faction and stay GDI gold. When playing Nod military vehicles should be remapped to gray and utility vehicles (MCV and harvester) should be remapped to red. This also applies to multiplayer colours.

True. They should remap. No idea how to apply the correct cameo right now.

> 
>     * There are a few alignment problems here and there. The unit and building portaits are a bit too large so they overflow certain things on the sidebar. If they were one pixel smaller from top and left I believe it would fix most of this.
> 
>     * The covert ops entries are so close they overlap each other.

Looks like another font spacing issue.

> 
>     * Missing "placeholder portaits when" (grey slabs) there are not enough units and buildings to fill the sidebar

This bug is also present on 640x400 version.

> 
>     * Campaign menu selects only GDI for some reason. Clicking on the Nod logo starts the GDI campaign.

This is related to the map selection problem I mentioned earlier. Check my `320x200-2` branch for a fix.

> 
>     * Tooltips remain stuck on the sidebar. Opening the pause menu fixes this.
> 

Looks like something has to be redraw every time the tooltips closes.

>     * Font letters are too far apart
> 
>     * Power meter is missing transparency

There is no transparency. If you look at the code, the sidebar meter is draw manually using lines, and the power meter is just a rectangle being draw at the correct place. Fixing this would include drawing the meter again over this rectangle.

> 
>     * Loading a lowres save in high res mode messes up in game UI elements and vice versa.

I remember this being a issue with C&C95 1024x768 High Resolution Patch. This might be another instance of this bug.

2021-07-04 06:09 UTC, hifi requested changes
Added some code review comments this time around. I know it's a bit annoying to get them in bursts but my time is quite limited right now.

2021-07-04 06:09 UTC, hifi commented on tiberiandawn/globals.cpp
> +char* title_pcx = NULL;
Globals should be in uppercase. This could be `TitlePicture`.

2021-07-04 06:09 UTC, hifi commented on tiberiandawn/init.cpp
> +    /* Finally, unload MS-DOS LOCAL.MIX and load Windows CCLOCAL.MIX file for the remaining assets. */
Can you explain why this is necessary? The DOS version would have not done this and this is looks hacky.

2021-07-04 06:09 UTC, hifi commented on tiberiandawn/sidebar.cpp
> +    char* repair_shp = "REPAIRF.SHP";
const

2021-07-04 06:09 UTC, hifi commented on common/settings.cpp
> +    Video.HighResolution = true;
This naming is a bit misleading in C&C context as "high resolution"  has meant adjustable resolution beyond 640x400. Possibly need a better name in the other direction.

2021-07-04 07:36 UTC, mvdhout1992 commented on common/settings.cpp
> +    Video.HighResolution = true;
Maybe HighResolution640x400?

2021-07-04 07:44 UTC, mvdhout1992 commented
The player palette sidebar cameo icons is done in StripClass::Draw_It(), the CC_Draw_Shape function has a palette argument IIRC and you can pass the player palette to it. See InfantryTypeClass::Draw_It() for an example, it's where the player infantry are house color remapped. The RA1 version of that function also has logic to remap the spy's color palette to the current house's palette and for drawing E1 (minigunner) instead of spy. RA1 also might have the player color remap logic in StripClass::Draw_It(). If you can't figure it out then just skip it. I could fix it in the future as I've done it before for RA1. I could implement it in the future.

The loading different reso savegames things is because the positions of the UI elements are stored in SidebarClass and StripClass. You need to add some extra logic to fix this. I suggest checking which Init/Reload/Init_IO() function is called when loading a savegame and then just recalculating the position of the broken UI elements then.

2021-07-04 14:05 UTC, giulianobelinassi commented on tiberiandawn/init.cpp
> +    /* Finally, unload MS-DOS LOCAL.MIX and load Windows CCLOCAL.MIX file for the remaining assets. */
The game seems to still require mission.ini from CCLOCAL.MIX. Furthermore, some fonts are not present in the DOS version and they still require loading for now. We can label this as a bug.

2021-07-04 14:07 UTC, giulianobelinassi commented on tiberiandawn/sidebar.cpp
> +    char* repair_shp = "REPAIRF.SHP";
The function which receives this as argument requires `char *`. That would require a cast from `const char *` to `char *`, which is forbidden by ISO C++. I could patch the function as well.

2021-07-04 14:08 UTC, giulianobelinassi commented on common/settings.cpp
> +    Video.HighResolution = true;
How about DOSResolutionMode?

2021-07-04 14:51 UTC, hifi commented on common/settings.cpp
> +    Video.HighResolution = true;
Just DOSMode sounds good to me 👍

There could be more DOS related behavioral things so it may be descriptive in the end.

2021-07-04 15:22 UTC, hifi commented on tiberiandawn/sidebar.cpp
> +    char* repair_shp = "REPAIRF.SHP";
Yeah it's better to const arguments if it doesn't require a massive search and replace.

If it would get annoying cast the argument so the stack variable stays const as mutable strings are already a problem.

2021-07-04 15:24 UTC, hifi commented on tiberiandawn/init.cpp
> +    /* Finally, unload MS-DOS LOCAL.MIX and load Windows CCLOCAL.MIX file for the remaining assets. */
Would explicit aliasing work with a comment the font is wrong but it still renders something?

Though don't know what to do with the mission ini.

2021-07-04 15:28 UTC, hifi commented
No need to fix saves at this point but I would just make those calculated at render time instead of storing them anywhere. We're not trying to run on a 486 anymore so such optimization is unnecessary in my opinion.

It's always more code trying to adjust instead of having a sound calculation in place.

2021-07-04 16:14 UTC, giulianobelinassi commented on tiberiandawn/init.cpp
> +    /* Finally, unload MS-DOS LOCAL.MIX and load Windows CCLOCAL.MIX file for the remaining assets. */
There is more. Language strings are present in LOCAL.MIX, and not loading this would load an old version which misses text from Covert Operations.

Perhaps the best solution is just require the Windows CCLOCAL.MIX for now until someone fix that in the future.

2021-07-04 16:32 UTC, hifi commented on tiberiandawn/init.cpp
> +    /* Finally, unload MS-DOS LOCAL.MIX and load Windows CCLOCAL.MIX file for the remaining assets. */
Okay, ideally we should be able to load both and their unique assets but we can keep this for now and add comments explaining why.

2021-07-04 17:07 UTC, mvdhout1992 commented
> 
> 
> No need to fix saves at this point but I would just make those calculated at render time instead of storing them anywhere. We're not trying to run on a 486 anymore so such optimization is unnecessary in my opinion.
> 
> Additionally having everything dynamic we could implement DOS/Win runtime toggle at some point (including adjustable resolution) without doing anything else than changing a few global variables and everything just snaps into place.
> 
> It's always more code trying to adjust instead of having a sound calculation in place.

The SidebarClass & StripClass classes already have some reinit function, if not we can add it and then just call it when necessary. The reason UI offets are saved is just a side effect of the games saving system, it's necessary for cameo icons to work properly.

I also fixed this issue for my hires branch, its not that much extra code.

2021-07-04 18:20 UTC, giulianobelinassi commented
Done. Added requested changes.

2021-07-05 10:45 UTC, hifi commented
I'm fine with this version with a little commit tweaking as I stepped through them: move "Read DOSMode option" as the first commit and remove the "// Test" bit completely from the history.

Bisecting these changes later as part of a larger bisect would be practically impossible (in normal hires mode) if the resolution gets borked when you hit a commit in-between.

If you feel you've done enough I can also do this while I'm going play testing.

2021-07-05 15:22 UTC, giulianobelinassi commented
Done.

2021-07-06 15:00 UTC, OmniBlade commented on tiberiandawn/sidebar.cpp
> +    char* repair_shp = "REPAIRF.SHP";
There is a PR to convert these all to const char, #615 specifically.

2021-07-06 17:48 UTC, hifi commented
I couldn't get vanilla to run with current remaster on wine with mingw built dlls. Need to do more digging because we really should test it properly.

2021-07-06 18:47 UTC, giulianobelinassi commented
> I couldn't get vanilla to run with current remaster on wine with mingw built dlls. Need to do more digging because we really should test it properly.

Can you bisect the commit that is causing the problem?

2021-07-06 19:15 UTC, hifi commented
Possibly if it's a regression but it's outside this PR as not even the vanilla branch worked on my laptop unfortunately.

2021-07-06 20:38 UTC, tore29 commented
Found another bug; DOS mode crashes on mega maps.

2021-07-06 20:44 UTC, giulianobelinassi commented
> Found another bug; DOS mode crashes on mega maps when radar is expanded.

Can you provide me a "mega map" to test?
Isn't that an instance of #648 ?

2021-07-06 21:00 UTC, tore29 commented
Mega map attached

[deathrace.zip](https://github.com/TheAssemblyArmada/Vanilla-Conquer/files/6772801/deathrace.zip)

2021-07-07 05:34 UTC, hifi commented
What DOS assets are in GENERAL.MIX? I've patched my C&C95 with CONQUER.MIX and LOCAL.MIX from the official demo and it seems to work relatively fine in dos and hires mode.

2021-07-07 05:56 UTC, hifi commented
Rebased and squashed the compat commits to the ones that introduce the incompatibility.

2021-07-07 11:51 UTC, hifi commented
Bisected the remaster crash to 80335d2950263ea51a0f589f9d7ee2a5eca19ee6

Need to figure out what went wrong.

2021-07-07 18:41 UTC, giulianobelinassi commented
> What DOS assets are in GENERAL.MIX? I've patched my C&C95 with CONQUER.MIX and LOCAL.MIX from the official demo and it seems to work relatively fine in dos and hires mode.

I simply copied these three files. If you report that it works without patching GENERAL.MIX, then GENERAL.MIX is not needed.

2021-07-13 06:21 UTC, hifi approved these changes
Finally got all the bits sorted to do my own smoke test, works great!

2021-07-13 06:27 UTC, merged