Replace assembly with verified C/C++ replacements.
TheAssemblyArmada/Vanilla-Conquer pull request #66
Opened 2020-07-16 21:39 UTC by OmniBlade

Different approach to ensure C replacements function the same/similarly enough compared to the asm code they replace. Intended to superceed #33.

2020-07-17 00:01 UTC, wdigger commented
Is there any reason to reimplement asm in C files with _cdecl calling convention? There are only a few C files in the project, clearly this is not the main trend.

2020-07-17 05:48 UTC, hifi commented
I would actually also want to drop the implicit cdecl because it either needs to be redefined globally for non-Windows builds (`__cdecl` is not defined by gcc on Linux). As far as I understand it is the default convention for plain functions for both C and C++ so it is redundant anyway.

2020-07-17 06:54 UTC, OmniBlade commented
Yeah I can start dropping the __cdecl stuff, it will date back to watcom whee the calling convention was register based by default.

2020-07-21 14:25 UTC, OmniBlade commented
Okay, reverted to using embeded data so the tests can be carried out even without being able to build asm on a given platform after discussion with @hifi and a view to future usefulness of the tests. Putting this up for merge now so the testing infrastructure is there to be added to and will add new functions in subsequent PRs.

2020-07-21 17:12 UTC, hifi requested changes

2020-07-21 17:12 UTC, hifi commented on CMakeLists.txt
> -option(MAP_EDITORRA "Include internal scenario editor in Red Alert build." OFF)
Whoops?

2020-07-21 19:19 UTC, OmniBlade commented on CMakeLists.txt
> -option(MAP_EDITORRA "Include internal scenario editor in Red Alert build." OFF)
Indeed, I'll get that fixed.

2020-07-22 09:55 UTC, hifi approved these changes
Builds and runs, tests pass with and without asm.

2020-07-22 09:56 UTC, merged