[TD] Readjust DOS sidebar and fonts
TheAssemblyArmada/Vanilla-Conquer pull request #676
Opened 2021-07-29 22:27 UTC by hifi

2021-07-29 22:46 UTC, giulianobelinassi requested changes

2021-07-29 22:46 UTC, giulianobelinassi commented on tiberiandawn/sidebar.cpp
> +        if (Get_Resolution_Factor() == 0) {
You should store Get_Resolution_Factor value on a variable instead of calling this function every time.

2021-07-29 22:46 UTC, giulianobelinassi commented on tiberiandawn/sidebar.cpp
> +    DownButton[ID].X = UpButton[ID].X + UpButton[ID].Width + ButtonSpacingOffset - (Get_Resolution_Factor() + 1);
Same thing here.

2021-12-02 12:50 UTC, hifi commented
I removed the WIP stuff and rebased. Each commit should describe the change correctly.

2021-12-03 01:52 UTC, giulianobelinassi approved these changes

2021-12-03 01:52 UTC, merged