Add option to use 4:3 aspect ratio when boxing
TheAssemblyArmada/Vanilla-Conquer pull request #689
Opened 2021-08-06 23:48 UTC by anpage

This adds an ini option to force a 4:3 aspect ratio when letterboxing is enabled. Pretty self-explanatory, but in my opinion this makes it closer to how it looked originally.

2021-08-07 05:33 UTC, hifi commented
Would it be make sense to make this a configurable option so you can force any aspect ratio? Default to empty string and take "w:h" in that is parsed to the corresponding floats.

2021-08-07 05:44 UTC, anpage commented
4:3 is the only one that makes sense to me, but I can definitely make that an option.

2021-08-07 05:57 UTC, hifi commented
I'm thinking displays with exceptionally weird physical dimensions so you can adjust it by hand. If it's not too much work to make it free form that would satisfy everyone in all cases. Thanks!

2021-08-07 21:43 UTC, anpage commented
How's this?

2021-08-08 03:37 UTC, hifi commented
This introduces the only try-catch we would have and it should default to an empty string which will make the option ignored. I don't know what to do with the exception handling, though. @OmniBlade?

2021-08-11 14:47 UTC, OmniBlade commented
I would suggest that this should be handled in the ini parser with a new Get/Set_Ratio function that returns a float representing the ratio and takes a default float that is returned on error in parsing with no exception handling as seems to be how other ini parsing is handled when the data can be incorrect?

2021-08-16 23:33 UTC, anpage commented
> I would suggest that this should be handled in the ini parser with a new Get/Set_Ratio function

I thought of this, but decided against it for a few reasons:

- It feels a little bit like premature optimization because it's extremely unlikely the game will ever need to read/write a ratio for any other reason. And if it ever does, it could just be moved to `ini.cpp` at that point.
- What would the default "ignored" value be? `0.0` isn't very ergonomic.
- A good `Put_Ratio()` implementation would be a challenge because floats can't represent all ratios. You'd either have to write some code to estimate the original ratio or just write the raw float, which feels wrong to me (4:3 would be an awkward `1.333333`). Less user-friendly for the same reason as `0.0` above. Representing the ratio as a string until needed seemed like the best choice.

> This introduces the only try-catch we would have

I'm not a very experienced C++ programmer, so I didn't think this would be a problem. What are the downsides to introducing exception handling? It would allow us to use nicer functions like `std::stof()` instead of `strtof()`.

I'm definitely willing to go whatever route you think is best, I'm just putting my thought process out there.

2021-08-17 08:28 UTC, OmniBlade commented
>     * It feels a little bit like premature optimization because it's extremely unlikely the game will ever need to read/write a ratio for any other reason. And if it ever does, it could just be moved to `ini.cpp` at that point.
>

This is pretty much how all other special cases of parsing a value are handled in the engine. It may well be a one off, but so is the parsing of the RSA keys from memory, it just encapsulates the logic.

> 
>     * What would the default "ignored" value be? `0.0` isn't very ergonomic.
>

The default is passed in on the Get_x call for most other parsing operations. You could pass it as a math operation, 4.0f / 3.0f for example to keep it tidy and the compiler will optimise it by calculating the result at compile time more than likely.

> 
>     * A good `Put_Ratio()` implementation would be a challenge because floats can't represent all ratios. You'd either have to write some code to estimate the original ratio or just write the raw float, which feels wrong to me (4:3 would be an awkward `1.333333`). Less user-friendly for the same reason as `0.0` above. Representing the ratio as a string until needed seemed like the best choice.
> 

This is true, you would have to implement conversion back to a fraction and is probably the trickiest part, but there are examples on the net for how to calculate a fraction from a decimal value.

> 
> > This introduces the only try-catch we would have
> 
> I'm not a very experienced C++ programmer, so I didn't think this would be a problem. What are the downsides to introducing exception handling? It would allow us to use nicer functions like `std::stof()` instead of `strtof()`.
> 
> I'm definitely willing to go whatever route you think is best, I'm just putting my thought process out there.

Its more that it isn't in keeping with the style of the original code given that its so old. At the time exception handling probably incurred more of a performance penalty than it does these days or programmers were just less familiar with it and thus less likely to try and use it.

I don't think we've really decided how we want to go with modernising the code. I fall more on the conservative side of making changes to it, but even I have used things like std::string where it was just easier than trying to manage C string buffers for path concatenation and such.

2021-11-17 22:50 UTC, OmniBlade commented
Looks like this is related to solving #512

2021-11-19 22:41 UTC, giulianobelinassi requested changes

2021-11-19 22:41 UTC, giulianobelinassi commented on common/video_sdl2.cpp
> +        try {
Don't use try-catch. This impacts performance negatively and we plan to build vanilla without exceptions for consoles support.

2022-04-26 12:23 UTC, giulianobelinassi approved these changes

2022-04-26 12:39 UTC, merged