Vanilla Conquer SDL1
TheAssemblyArmada/Vanilla-Conquer pull request #694
Opened 2021-10-03 18:24 UTC by arczi84

With Big Endian patches

2021-10-18 22:52 UTC, giulianobelinassi requested changes
This pull request should be separated into two pull requests: one introducing the SDL1 port, and another fixing the big endian issues. Also it shouldn't interfere with the SDL2 video engine, and both engines should be compiling on the pull request.

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> +option(BUILD_VANILLARA "Build Red Alert executable." OFF)
You shoudn't need to disable the RA build here. If you wan't to not build RA, you can call cmake with
```
cmake <path_to_CMakeList.txt> -DBUILD_VANILLARA=no
```

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> +option(SDL1 "Enable SDL1 video backend." ON)
SDL2 should remain default. If you want that SDL1 be the default build in some system (amiga, for instance), you can make the toolchain file define some variable and then test for that in this file. If true, then disable SDL2 and enable SDL1.

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> +    set(SDL1 ON)
This should be off. This is the case where the games aren't build, but I assume the MIX tools are.

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> +		link_directories(/mingw64/lib)
This is a hardcoded directory that will only work when targeting Windows. Instead you should write some script like the SDL finder on cmake folder to find the SDL libraries.

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> -    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -fcheck-new -fsigned-char -fdata-sections -ffunction-sections -DNOMINMAX")
I am not sure why did you remove some flags. Are you using an old version of GCC?

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> +    #-ffunction-sections -fdata-sections <- won't compile on Amiga
If amiga doesn't support that, you should test for amiga platform. If false, then add the original flags, but on true, simply don't add those flags.

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> +    include_directories("/usr/include/SDL")
Hardcoded directory

2021-10-18 22:52 UTC, giulianobelinassi commented on CMakeLists.txt
> +	if (uname MATCHES "MSYS_NT-10.0-19042")
Isn't it valid on newer `MSYS_NT` builds? Why test for equality?

2021-10-18 22:52 UTC, giulianobelinassi commented on common/crc.cpp
> +            CRC = lrotl(CRC, 1) + le32toh(*longptr++);
You should split this pull request into two pull requests: One adds SDL1 support for vanilla, and the other fix the big endian issues.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/crc.h
> +#include <stdio.h>
`stdio.h` included, but no stdio.h function called.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/framelimit.cpp
> -#ifdef SDL2_BUILD
You should modify that to
```
#if defined(SDL2_BUILD) || defined(SDL_BUILD)
```

so that this code runs in both build options. This code is required by the SDL2 frontend.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/framelimit.cpp
> -#ifdef SDL2_BUILD
Same here...

2021-10-18 22:52 UTC, giulianobelinassi commented on common/framelimit.cpp
> -#ifdef SDL2_BUILD
... and here.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/keyframe.cpp
> +#include <stdio.h>
`stdio.h` included but no `stdio.h` functions called.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/load.cpp
> -    uncomp_size = Reverse_Long(uncomp_size);
Maybe fixing `Reverse_Long` relieves you from some work?

2021-10-18 22:52 UTC, giulianobelinassi commented on common/mixfile.h
> +    Count = le16toh(fileheader.count);
Maybe the byteswap should be done when reading the filereader?

2021-10-18 22:52 UTC, giulianobelinassi commented on common/mixfile.h
> +    if ((*(int32_t const*)ptr1) < le32toh(*(int32_t const*)ptr2))
Are you sure this is correct? this is a compare function for qsort or bsearch, so you may still be comparing correct values with incorrect ones because the other value wasn't byte swapped.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/video_sdl1.cpp
> +#ifdef SDL2
the SDL1 video file shouldn't need any macro for SDL2 compiling.

Also run `clang-format -i *.cpp *.h`  on the folder so that the code is automatically indented correctly.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwkeyboard.h
> -#ifdef SDL2_BUILD
`#if defined(SDL2_BUILD) || defined(SDL1_BUILD)`

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwmouse.cpp
> +#ifdef SDL_BUILD
`

#if defined(SDL2_BUILD) || defined(SDL1_BUILD)`

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwmouse.cpp
> +#if defined(REMASTER_BUILD) || defined(SDL_BUILD)
Same thing here...

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwmouse.cpp
> -#if defined(REMASTER_BUILD) || defined(SDL2_BUILD)
... and here...

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwmouse.cpp
> -#if defined(SDL2_BUILD)
... and here ...

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwmouse.cpp
> -#ifdef SDL2_BUILD
... and here.

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwstd.h
> +#if 0//ndef AMIGA
Please remove this strupr code, because...

2021-10-18 22:52 UTC, giulianobelinassi commented on common/wwstd.h
>      for (int i = 0; i < strlen(str); i++)
this is just silly. This function is calling strlen on every iteration, which is O(n). Therefore this function consumes O(n²) for doing string uppercase, which is not acceptable by any means. Any libc implementation of this function should be better than this.

2021-10-18 22:52 UTC, giulianobelinassi commented on tiberiandawn/init.cpp
> +#ifndef AMIGA
I assume this is here because an early problem?

2021-10-18 22:52 UTC, giulianobelinassi commented on tiberiandawn/startup.cpp
> -#if defined(SDL2_BUILD)
`#if defined ...`

2021-10-18 22:52 UTC, giulianobelinassi commented on tiberiandawn/winstub.cpp
> -#ifdef SDL2_BUILD
`#if defined(SDL2_BUILD) || defined(SDL_BUILD)`

2021-10-18 22:52 UTC, giulianobelinassi commented on tiberiandawn/winstub.cpp
> -#ifdef SDL2_BUILD
`#if defined(SDL2_BUILD) || defined(SDL_BUILD)`

2021-10-18 22:52 UTC, giulianobelinassi commented on tiberiandawn/winstub.cpp
> -#ifndef SDL2_BUILD
`#if defined(SDL2_BUILD) || defined(SDL_BUILD)`

2021-10-18 22:52 UTC, giulianobelinassi commented on tiberiandawn/winstub.cpp
> -#if defined(SDL2_BUILD)
`#if defined(SDL2_BUILD) || defined(SDL_BUILD)`

2021-10-19 07:26 UTC, arczi84 commented on CMakeLists.txt
> +option(BUILD_VANILLARA "Build Red Alert executable." OFF)
I should not make  a pull request, just wanted to share SDL1 code for other BE ports.

2021-10-19 07:53 UTC, arczi84 commented on common/wwmouse.cpp
> +#ifdef SDL_BUILD
SDL_BUILD is enabled of both SDL1 and 2 to avoid double #if like you suggested.

2021-10-19 08:51 UTC, arczi84 commented on common/video_sdl1.cpp
> +#ifdef SDL2
I left this so you can compare with SDL2 and decide if use one file for both SDL's.

2021-10-19 09:21 UTC, arczi84 commented on common/wwstd.h
> +#if 0//ndef AMIGA
...multiple definition on linking.
Add #if HAVE_STRUPR.

2021-10-19 09:24 UTC, arczi84 commented on common/mixfile.h
> +    if ((*(int32_t const*)ptr1) < le32toh(*(int32_t const*)ptr2))
I have compared this swapped values with LE  and this solution looked correct.
Files started to load from .MIX.

2021-10-19 09:44 UTC, arczi84 commented on common/load.cpp
> -    uncomp_size = Reverse_Long(uncomp_size);
It's only used here.

But using le32toh in Reverse_Long() might be faster?

2021-10-19 09:51 UTC, arczi84 commented on tiberiandawn/init.cpp
> +#ifndef AMIGA
Yes, it's fixed now.

2021-10-19 10:11 UTC, arczi84 commented on common/framelimit.cpp
> -#ifdef SDL2_BUILD
I think you misunderstood it. SDL_BUILD is used for both SDL's and there is separate  SDL1_BUILD define.

2021-10-19 19:58 UTC, giulianobelinassi commented on common/load.cpp
> -    uncomp_size = Reverse_Long(uncomp_size);
Well, if it is only used there, then it is safe to remove it. :)

2022-05-22 13:20 UTC, closed without merging