Vanilla Conquer Sdl 1.2
TheAssemblyArmada/Vanilla-Conquer pull request #697
Opened 2021-10-24 16:39 UTC by arczi84

Initial SDL 1.2 support.
Only VanillaTD.

2021-10-24 21:40 UTC, giulianobelinassi requested changes

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl1.h
> +
Missing headerguard.
```
#ifndef VIDEO_SDL1_H
#define VIDEO_SDL1_H
```

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl1.h
> +}
`#endif // VIDEO_SDL1_H`

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl1.h
> +int
All these functions should be declared `static`. I assume they won't be visible in any compilation unit other than `video_sdl2.cpp`.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl1.h
> +        //SDL_FreePalette(format->palette);
This if can be simply removed.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl1.h
> +	//SDL_free(palette);
Why is this code commented out? If they serve no purpose, it can simply be deleted.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl1.h
> +inline void
Why are you using GNU-style C function declarations? please run
```
clang-format -i <file.h>
```
for it to be automatically formated according to this project coding style.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl1.h
> +inline SDL_Palette *
Even the `inline` functions should be declared `static`, as it avoids generating symbols for it and duplicated code.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl2.cpp
I guess this file should be renamed to `video_sdl.cpp` if they now contain code for both sdl1 and sdl2.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl2.cpp
> +	int win_w = 640;
Incorrect indentation. Also I think you should only guard the `SDL_GetRendererOutputSize` if sdl2 build, and default the variable to 640x400.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl2.cpp
> +    	window = SDL_SetVideoMode(w, h, 16/*bits_per_pixel*/, SDL_HWSURFACE);
I assume 16bpp isn't the most used video mode around? This should be read from a configuration file, and default to 24bpp if none was provided.

You could also default according to the operating system. I guess for Windows 95/.../XP, 8bpp is safe. For later versions, 32bpp is what most people use.

2021-10-24 21:40 UTC, giulianobelinassi commented on common/video_sdl2.cpp
> +		SDL_BlitSurface(surface, NULL, window, NULL);
Incorrect indentation.

2021-10-25 03:27 UTC, hifi commented on common/video_sdl2.cpp
> +    	window = SDL_SetVideoMode(w, h, 16/*bits_per_pixel*/, SDL_HWSURFACE);
I'd make the PixelFormat setting an ifdef between SDL1 and SDL2 adding a BitDepth for the former in settings.

2021-10-26 00:03 UTC, giulianobelinassi commented
I had to apply the following patch for it to compile:

[0001-Add-cmake-script-for-finding-SDL1.zip](https://github.com/TheAssemblyArmada/Vanilla-Conquer/files/7414144/0001-Add-cmake-script-for-finding-SDL1.zip)

Also, this happens when I execute vanillatd:

![Screenshot from 2021-10-25 20-53-21](https://user-images.githubusercontent.com/7212952/138786880-0f395a26-a35c-456e-86c6-8d57ae540f21.png)

2021-11-05 10:57 UTC, arczi84 commented on common/video_sdl1.h
> +	//SDL_free(palette);
They are present in sdl2 code but crash here.

2022-05-22 13:20 UTC, closed without merging