[TD] Get the game to boot with retail DOS version files
TheAssemblyArmada/Vanilla-Conquer pull request #700
Opened 2021-11-02 02:51 UTC by giulianobelinassi

This PR gets TD to run using solely the files provided by retail DOS discs. It also fixes the scorecreen and get the earth_[ea].wsa to load and fixed some graphical glitches there, but not all: it is not erasing text in some frames.

2021-11-02 03:03 UTC, hifi commented on tiberiandawn/startup.cpp
> +        if (Settings.Video.DOSMode || Is_Demo() || Is_DOS_Files()) {
Do we really want to force DOSMode if LOCAL.MIX exists? Shouldn't we check the other way around that if the hires version doesn't exist it would "downgrade" to DOSMode?

2021-11-02 03:03 UTC, hifi commented on tiberiandawn/conquer.cpp
> -        bAlreadyChecked = true;
Why? :sweat_smile:

2021-11-02 03:03 UTC, hifi commented on tiberiandawn/conquer.cpp
> +    if (!already_checked) {
See the comment later, we should probably do a reverse check as well.

2021-11-02 20:19 UTC, giulianobelinassi commented on tiberiandawn/startup.cpp
> +        if (Settings.Video.DOSMode || Is_Demo() || Is_DOS_Files()) {
Fixed.

2021-11-02 20:20 UTC, giulianobelinassi commented on tiberiandawn/conquer.cpp
> -        bAlreadyChecked = true;
Assume that we are not running Demo. Then the function will check for file existence every time it was called.

2021-11-22 14:58 UTC, OmniBlade requested changes
There are some font drawing issues on the map and score screens, but I assume they are ongoing issues with DOS support and not specific to this PR.

2021-11-22 14:58 UTC, OmniBlade commented on tiberiandawn/conquer.cpp
> -        bAlreadyChecked = true;
Are you sure about that? bAlreadyChecked will be unconditionally set the first run through and then only checked from then on as its a static variable.

2021-11-22 14:58 UTC, OmniBlade commented on tiberiandawn/conquer.cpp
> +    if (!already_checked) {
Again, with already_checked being static, there is no need to set it each time, it should just be set in the if block the first time through the function.

2021-11-22 15:02 UTC, giulianobelinassi commented on tiberiandawn/conquer.cpp
> -        bAlreadyChecked = true;
True. We should simply drop the last commit

2021-12-01 23:47 UTC, OmniBlade approved these changes

2021-12-02 00:15 UTC, merged