[RA] Fixes briefing drawing speed.
TheAssemblyArmada/Vanilla-Conquer pull request #705
Opened 2021-11-21 23:08 UTC by OmniBlade

Text was being drawn limited by the frame limiter which slowed the draw
down too much vs the original. Replaced with unconditional thread yield
and frame draw.

Fixes #698
Fixes #531
Partly solves #642

2021-11-23 05:54 UTC, hifi requested changes
I don't like that the rendering doesn't honor the frame limit if implemented like this. Maybe we could add an argument to Frame_Limiter to prevent blocking so it would render a frame only if it's time to do it?

Alternatively we could have a different function to do this. Then the sleep would only slow down the loop to keep its timing somewhat consistent and it could even be timed correctly just like a frame limiter so it's consistent.

2021-11-23 10:13 UTC, OmniBlade commented
@hifi I've refactored it to include a "no_block" parameter for the frame limiter as suggested.

2021-12-03 01:02 UTC, giulianobelinassi commented
I think it is appropriate to add a single variable `flags` to framelimiter, else every time a new flag is necessary for frame limiter we need to pass a lot of arguments to it.

I suggest something like:
```
typedef enum {
  FL_NONE,
  FL_FORCEDRAW = 1 << 0,
  FL_NOBLOCK = 1 << 1,
} FrameLimiterFlags;
```

void Frame_Limiter(FrameLimiterFlags flags);

2021-12-04 00:29 UTC, giulianobelinassi commented
Here is a patch which can be applied on top of this commit to illustrate what I mean:

```
diff --git a/common/framelimit.cpp b/common/framelimit.cpp
index 24db55b..ac6c359 100644
--- a/common/framelimit.cpp
+++ b/common/framelimit.cpp
@@ -15,7 +15,7 @@ extern WWMouseClass* WWMouse;
 void Video_Render_Frame();
 #endif
 
-void Frame_Limiter(bool force_render, bool no_block)
+void Frame_Limiter(FrameLimitFlags flags)
 {
     static auto frame_start = std::chrono::steady_clock::now();
 #ifdef SDL2_BUILD
@@ -24,8 +24,8 @@ void Frame_Limiter(bool force_render, bool no_block)
     auto render_start = std::chrono::steady_clock::now();
     auto render_remaining = std::chrono::duration_cast<std::chrono::milliseconds>(frame_start - render_start).count();
 
-    if (force_render == false && render_remaining > render_avg) {
-        if (!no_block) {
+    if (!(flags & FrameLimitFlags::FL_FORCE_RENDER) && render_remaining > render_avg) {
+        if (!(flags & FrameLimitFlags::FL_NO_BLOCK)) {
             ms_sleep(unsigned(render_remaining));
         } else {
             ms_sleep(1); // Unconditionally yield for minimum time.
@@ -42,7 +42,7 @@ void Frame_Limiter(bool force_render, bool no_block)
     render_avg = (render_avg + render_time) / 2;
 #endif
 
-    if (Settings.Video.FrameLimit > 0 && !no_block) {
+    if (Settings.Video.FrameLimit > 0 && !(flags & FrameLimitFlags::FL_NO_BLOCK)) {
 #ifdef SDL2_BUILD
         auto frame_end = render_end;
 #else
diff --git a/common/framelimit.h b/common/framelimit.h
index 3ee0b39..b5212fe 100644
--- a/common/framelimit.h
+++ b/common/framelimit.h
@@ -1,6 +1,13 @@
 #ifndef FRAMELIMIT_H
 #define FRAMELIMIT_H
 
-void Frame_Limiter(bool force_render = true, bool no_block = false);
+enum FrameLimitFlags
+{
+    FL_NONE = 0,
+    FL_FORCE_RENDER = 1 << 0,
+    FL_NO_BLOCK = 1 << 1,
+};
+
+void Frame_Limiter(FrameLimitFlags flags = FL_FORCE_RENDER);
 
 #endif /* FRAMELIMIT_H */
diff --git a/redalert/conquer.cpp b/redalert/conquer.cpp
index 3894475..d11e5ff 100644
--- a/redalert/conquer.cpp
+++ b/redalert/conquer.cpp
@@ -1684,7 +1684,7 @@ static void Sync_Delay(void)
             Map.Render();
         }
 
-        Frame_Limiter(false);
+        Frame_Limiter(FL_NONE);
     }
     Color_Cycle();
     Call_Back();
diff --git a/redalert/scenario.cpp b/redalert/scenario.cpp
index 6d91890..2b1cd31 100644
--- a/redalert/scenario.cpp
+++ b/redalert/scenario.cpp
@@ -1635,7 +1635,7 @@ int BGMessageBox(char const* msg, int btn1, int btn2)
                 Call_Back();
             } while (!Keyboard->Check() && cd);
         }
-        Frame_Limiter(false, true);
+        Frame_Limiter(FL_NO_BLOCK);
     } while (buffer[++bufindex]);
 
     Show_Mouse();
diff --git a/tiberiandawn/conquer.cpp b/tiberiandawn/conquer.cpp
index cb30d6b..84a540f 100644
--- a/tiberiandawn/conquer.cpp
+++ b/tiberiandawn/conquer.cpp
@@ -1513,7 +1513,7 @@ static void Sync_Delay(void)
             Map.Render();
         }
 
-        Frame_Limiter(false);
+        Frame_Limiter(FL_NONE);
     }
     Color_Cycle();
     Call_Back();
```

2021-12-04 00:30 UTC, giulianobelinassi approved these changes

2021-12-08 16:16 UTC, OmniBlade commented
Broken by vanilla-conquer no longer being treated as a fork of the EA repo, see #709 instead.

2021-12-08 16:16 UTC, closed without merging