Cleanup common types for portability
TheAssemblyArmada/Vanilla-Conquer pull request #72
Opened 2020-07-23 15:35 UTC by hifi

There's a lot of Windows types and `__cdecl` around. Replace with standard types for now.

2020-07-24 21:36 UTC, wdigger commented on common/soundio.cpp
>      Init_Locked_Data();
Is it possible to remove `window` parameter at all? I removed it from video initialisation, cause it's just global variable in fact.
It would be ideal if this global variable is not used outside of the platform-specific implementation.

2020-07-25 04:39 UTC, hifi commented on common/soundio.cpp
>      Init_Locked_Data();
Indeed, I changed it.

2020-07-26 06:40 UTC, hifi commented
In addition to the small cleanups here I made the CMake configuration able to do native builds without needing to hack CMakeLists and defaulted to debug build with symbols for single-configuration targets (like make). I've had to recompile the whole project so many times when I end up with a crash and there is no debug symbols.

So to test native builds on Linux I use:
```
cmake .. -DCMAKE_TOOLCHAIN_FILE= -DDDRAW=OFF -DDSOUND=OFF -DNETWORKING=OFF
```

2020-07-27 14:05 UTC, OmniBlade requested changes
Line 232 in soundint.h needs changing to match the signature of the actual callback function.

2020-07-30 10:51 UTC, OmniBlade approved these changes

2020-07-30 10:51 UTC, merged