Adds GitHub workflows for Windows x86 builds.
TheAssemblyArmada/Vanilla-Conquer pull request #74
Opened 2020-07-25 22:20 UTC by OmniBlade

Adds GitHub workflows to build msvc and mingw-w64 Windows x86 builds. Format test only done in mingw-w64 build.

2020-07-26 05:22 UTC, hifi requested changes
Can we somehow test this flow within the PR?

2020-07-26 05:22 UTC, hifi commented on .github/workflows/mingw.yml
> +        curl -L -O https://www.japheth.de/Download/JWasm/JWasm211as.zip
I wouldn't hit this poor chaps personal website for every build. Can we at least mirror it on GitHub or use the JWasm GH project releases (not from the same author, though)?

2020-07-26 14:30 UTC, OmniBlade commented on .github/workflows/mingw.yml
> +        curl -L -O https://www.japheth.de/Download/JWasm/JWasm211as.zip
I'll host it on github, we know its the same source that way which seems to work. Regarding testing, it doesn't look like it will start testing until its part of this repo proper, but they both succeed on my github mirror of the project.

2020-07-26 21:49 UTC, OmniBlade commented on .github/workflows/mingw.yml
> +        curl -L -O https://www.japheth.de/Download/JWasm/JWasm211as.zip
Changed my mind and just pull the github version which looks like its just a continuation of the project on that website. Builds and compiles the C&C code at any rate.

2020-07-27 10:15 UTC, hifi approved these changes
Can't properly review it but this looks okay on paper :sweat_smile:

2020-07-27 11:05 UTC, hifi commented on .github/workflows/mingw.yml
> +        git clone https://github.com/JWasm/JWasm.git jwasm
Actually use the commit zip instead rather than clone, less downloading?

2020-07-27 13:59 UTC, merged

2020-07-27 14:17 UTC, ShFil119 commented
I'd suggest later to use bintray. It doesn't have limited life time as appveyor (6m) or actions (90d).

2020-07-27 15:34 UTC, hifi commented
I don't see it necessarily that useful. We will do releases as GitHub releases which don't have a time limit.