Cleans up remaining warnings in MSVC builds
TheAssemblyArmada/Vanilla-Conquer pull request #740
Opened 2022-01-29 23:34 UTC by OmniBlade

Cleans up game code related warnings issued by MSVC, builds cleanly at current warnings level for both 64bit and 32bit builds.

2022-03-16 00:17 UTC, giulianobelinassi requested changes

2022-03-16 00:17 UTC, giulianobelinassi commented on common/tcpip.cpp
> +#define WM_UDPASYNCEVENT (WM_USER + 116) // UDP socket Async event
Shoudn't this somehow change the behaviour? These are used on a parameter to `WSAAsyncSelect();`

2022-03-16 00:17 UTC, giulianobelinassi commented on redalert/session.h
> +    bool Bases;
Is this a good idea? Is sizeof(bool) the same on all platforms?

2022-03-16 00:17 UTC, giulianobelinassi commented on redalert/taction.cpp
> +        DBG_ERROR("NewINIFormat < 2 is an unsupported map format. Trigger actions will not be loaded correctly.");
Is there evidence that no official map has NewINIFormat < 2?

2022-03-16 00:17 UTC, giulianobelinassi commented on redalert/iconset.cpp
> -void* Load_Icon_Set(char const* filename, void* iconsetptr, long buffsize)
Tile.h declares a prototype for this function. Remove this as well.

2022-03-16 08:59 UTC, OmniBlade commented on common/tcpip.cpp
> +#define WM_UDPASYNCEVENT (WM_USER + 116) // UDP socket Async event
WSAAsyncSelect() is only used if SDL2 isn't which we aren't actually supporting but I guess technically it could.

2022-03-16 09:02 UTC, OmniBlade commented on redalert/taction.cpp
> +        DBG_ERROR("NewINIFormat < 2 is an unsupported map format. Trigger actions will not be loaded correctly.");
The only map I know of that isn't higher than 2 is from the leaked beta and has none set at all as well as is missing its mappack section.

2022-03-16 09:06 UTC, OmniBlade commented on redalert/session.h
> +    bool Bases;
Hmm, potentially not, I could add a static_assert to ensure it is at compile time since all the platforms we care about bool is currently 1.

2022-03-16 23:39 UTC, giulianobelinassi commented on redalert/session.h
> +    bool Bases;
I'd still use char or int for this struct to keep its size as expected.

2022-04-10 22:28 UTC, OmniBlade commented on redalert/session.h
> +    bool Bases;
Doesn't look like the struct is passed over the network, so keeping the size of the struct consistent doesn't look to be an issue.

2022-04-11 14:05 UTC, giulianobelinassi approved these changes
I've updated some comments. The PR is approved nevertheless.

2022-04-11 14:05 UTC, giulianobelinassi commented on common/tcpip.cpp
> +#define WM_UDPASYNCEVENT (WM_USER + 116) // UDP socket Async event
This #have been updated to match wsproto.h. I see. Should this file include wsproto.h in that case?

2022-04-11 14:05 UTC, giulianobelinassi commented on tiberiandawn/saveload.cpp
> +            uintptr_t target_as_object_ptr = reinterpret_cast<uintptr_t>(selection[j]);
Red Alert has TARGET_SAFE_CAST for this. Do you think it is worth porting this to TD?

2022-04-26 08:26 UTC, merged