Makes Windows and Linux 64bit builds compatible for network games.
TheAssemblyArmada/Vanilla-Conquer pull request #742
Opened 2022-02-17 23:16 UTC by OmniBlade

Currently can create an join each others games but desyncs immediately.

2022-04-11 15:18 UTC, giulianobelinassi requested changes
There are a few concerns about changing the type of memory functions to int32 on 64-bits systems. Functions like Mem_Copy, Add_Long_To_Pointer, and others should not have its size parameter turned 32-bits. Instead, they should match the pointer size.

There is also the MEM_CHECK case which seems to be broken in a way before and now it is broken in another way. I think it is worth at least gettiing the size of things right.

There is also a comment about if it is worth expanding the Frame variable from 32-bits to 64-bits for longer games support.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> +unsigned int Largest_Mem_Block(void);
Limiting those functions to 32-bit integers return values could be a problem on 64-bit machines. Overflow can bug the game to think that not enough memory is available and problems like that.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> +unsigned int MinRam = 0L; // Record of least memory at worst case.
Same thing here. It is handling memory-related stuff.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> +    unsigned int* magic_ptr = (unsigned int*)(((char*)mem_ptr) - 16);
Looks this was broken on 64-bits already, but this code break it in another way.

You should keep it to match pointer size. And also update the difference offset so it matches the size of the type.

You can use size_t and ssize_t for that.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> +        unsigned int* magic_ptr = (unsigned int*)(((char*)pointer) - 16);
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> +void* Resize_Alloc(void* original_ptr, unsigned int new_size_in_bytes)
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> +int Ram_Free(MemoryFlagType)
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> -long Heap_Size(MemoryFlagType)
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/alloc.cpp
> -long Total_Ram_Free(MemoryFlagType)
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/bitfields.h
> +#define BITFIELD_STRUCT
I would check if __MSVC__ is defined to define this macro as empty. on other compilers, then check if NETWORKING is defined. If yes, then issue an #error to abort compilation and tell the user that network capabilities can not be enabled due to unsupported compiler.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/blowfish.cpp
> +    unsigned int left = 0x00000000L;
you are assigning an long (0x0L) to an int. I think GCC will issue a warning here.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/drawbuff.h
> +int Buffer_Size_Of_Region(void* thisptr, int w, int h);
This also seems to be related to memory. Please use ssize_t if this case.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/drawbuff.h
> -long Buffer_To_Page(int x, int y, int w, int h, void* Buffer, void* view);
same thing here.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/field.cpp
>      case TYPE_UNSIGNED_LONG:
I think this should be documented somewhere that the game expect TYPE_LONG and TYPE_UNSIGNED_LONG are expected to be 32-bits.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/field.cpp
>      case TYPE_UNSIGNED_LONG:
Or change those things to TYPE_INT32 and TYPE_UINT32

2022-04-11 15:18 UTC, giulianobelinassi commented on common/ipx.h
> +    int edi;
Shouldn't this be unsigned? Nevertheless, since the orginal code is like this...

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> -    unsigned long offcurr, offdiff;
This seems to be ptrdiff result.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +    ptr = (char*)Add_Long_To_Pointer(dataptr, (((unsigned int)framenumber << 3) + sizeof(KeyFrameHeaderType)));
This should be the same size as pointer. So, ptrint_t shoud be the way to go.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +            ptr = (char*)Add_Long_To_Pointer(dataptr, (((unsigned int)currframe << 3) + sizeof(KeyFrameHeaderType)));
Same thing here.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +            Mem_Copy(ptr, &offset[0], (int)(SUBFRAMEOFFS * sizeof(uint32_t)));
Mem_Copy should accept a ssize_t instead of int because it is a memory-related function.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +        off16 = (unsigned int)lockptr & 0x00003FFFL;
Cast it to uintptr_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +            off16 = (unsigned int)ptr & 0x00003FFFL;
uintptr_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +                    off16 = (unsigned int)lockptr & 0x00003FFFL;
uintptr_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +                        (int)(SUBFRAMEOFFS * sizeof(uint32_t)));
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +            if (THEATERSHPBUF_AVAILABLE(temp_shape_ptr) < (int)length && !AllowBigShapeBufRealloc) {
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +            if (BIGSHPBUF_AVAILABLE(temp_shape_ptr) <= (int)length) {
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/keyframe.cpp
> +            ((((int)sizeof(unsigned int) << 1) * ((KeyFrameHeaderType*)dataptr)->frames) + 16
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/memflag.h
> +int Ram_Free(MemoryFlagType flag);
Be careful with memory-related functions, as I mentioned early.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/newdel.cpp
> +    return (Alloc((unsigned int)size, MEM_NEW));
size_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/newdel.cpp
> +    return (Alloc((unsigned int)size, MEM_NEW));
size_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/palette.cpp
> +    int t;     // Working tick intermediate value.
Trailing whitespace.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/rawfile.h
> +        return (int)((unsigned)UINT_MAX) - 16L;
This clearly is wrong. Casting this value to int will overflow.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/soundio_openal.cpp
> +        FileStreamBuffer = malloc((unsigned int)(LockedData.StreamBufferSize * LockedData.StreamBufferCount));
ssize_t

2022-04-11 15:18 UTC, giulianobelinassi commented on common/wwalloc.h
> -void* cdecl Resize_Alloc(void const* original_ptr, unsigned long new_size_in_bytes);
memory related fnct

2022-04-11 15:18 UTC, giulianobelinassi commented on common/wwstd.h
> +// int ABS(int);
simply delete those.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/wwstd.h
> +// int MIN(int, int);
and this.

2022-04-11 15:18 UTC, giulianobelinassi commented on common/wwstd.h
>  // Merges to shorts to become a long
rename to MAKE_INT32?

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/conquer.cpp
> +unsigned int Disk_Space_Available(void)
size_t

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/externs.h
> +extern int Frame;
This could be a problem on long games, no? perhaps expanding to int64_t?

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/function.h
> +unsigned int Disk_Space_Available(void);
size_t

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/ipxgconn.h
> +    unsigned int LastPacketID[4];   // array of last 4 packet ID's
Trailing Whitespace.

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/miscasm.cpp
> +void Mem_Copy(void const* source, void* dest, unsigned int bytes_to_copy)
size_t

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/queue.cpp
> +    static int their_frame[MAX_PLAYERS - 1];           // other players' frame #'s
this is also related to frame.

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/session.h
> +            unsigned int MinVersion;           // min version this game supports
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/session.h
> +            unsigned int MaxVersion;           // max version this game supports
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/session.h
> +            unsigned int ResponseTime;         // packet response time
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/session.h
> +            unsigned int NameCRC;         // CRC of sender's Game Name
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/session.h
> +            unsigned int ID;       // unique ID for this chat node
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/session.h
> +    int TrapFrame;             // frame # to start trapping 'TrapObject'
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/team.cpp
> +        int x = 0;                    // Accumulated X coordinate.
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/teamtype.cpp
> +// int vtypes, bool alerted)
Erase?

2022-04-11 15:18 UTC, giulianobelinassi commented on redalert/tevent.h
> +        int Value;             // Used for other events that need data.
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on tiberiandawn/function.h
> +unsigned int Disk_Space_Available(void);
size_t

2022-04-11 15:18 UTC, giulianobelinassi commented on tiberiandawn/noseqcon.cpp
> +    unsigned int curtime;       // current time
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on tiberiandawn/session.h
> +            unsigned int NameCRC;            // CRC of sender's Game Name
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on tiberiandawn/session.h
> +            unsigned int ID;     // unique ID for this chat node
Trailing Whitespace

2022-04-11 15:18 UTC, giulianobelinassi commented on tiberiandawn/stats.cpp
> -        fileo.Read(abuffer, _ShapeBufferSize - 1);
looks like abuffer isn't used anymore, hence it can be removed?

2022-04-11 15:18 UTC, giulianobelinassi commented on tiberiandawn/stats.cpp
> +        build_time = hton64(build_time);
Perhaps gather which platform hte player is using?

2022-04-11 15:36 UTC, OmniBlade commented on tiberiandawn/stats.cpp
> -        fileo.Read(abuffer, _ShapeBufferSize - 1);
Isn't that exactly what I've done here? :D

2022-04-25 15:18 UTC, OmniBlade commented on tiberiandawn/noseqcon.cpp
> +    unsigned int curtime;       // current time
These whitespace changes are due to clang-format.

2022-04-25 22:09 UTC, giulianobelinassi approved these changes

2022-04-25 22:09 UTC, giulianobelinassi commented
Keep up the good work!

2022-04-26 08:49 UTC, merged