Reimplement rect related ASM functions with C
TheAssemblyArmada/Vanilla-Conquer pull request #76
Opened 2020-07-27 18:27 UTC by wdigger

2020-07-29 13:07 UTC, hifi commented
This looks good to me. Could you rebase and fix the test CMakeLists so the CI picks it up? I just fixed GH Actions tests this morning.

We will do a refactor/cleanup for test CMakeLists later.

2020-07-30 14:59 UTC, OmniBlade requested changes

2020-07-30 14:59 UTC, OmniBlade commented on common/CMakeLists.txt
> +    rectasm.c
The original name for the file that contained the clip rect functions was cliprect.asm that looks like it was turned into inline asm for the remaster, perhaps use cliprect.c, especially since it doesn't actually contain any asm code?

2020-07-30 14:59 UTC, OmniBlade commented on common/rect.h
> +#ifdef __cplusplus
I'd rather the Clip rect functions be moved to their own header and have that included in this header rather than the ifdef magic around the C++ classes.

2020-07-30 15:29 UTC, wdigger commented on common/CMakeLists.txt
> +    rectasm.c
Done

2020-07-30 15:31 UTC, wdigger commented on common/rect.h
> +#ifdef __cplusplus
It's a bad idea for temporary solution (ASM and C implementations), cause in this case I need to add header to files where those functions are used.

2020-07-30 17:53 UTC, OmniBlade commented on common/rect.h
> +#ifdef __cplusplus
Just add the cliprect.h to the rect.h, then no need to change any other files, but it will keep all the cplusplus checks out of the way of actual c++ code.

2020-07-30 18:13 UTC, wdigger commented on common/rect.h
> +#ifdef __cplusplus
It's a terrible practice when headers included in files where not used.

2020-07-30 18:16 UTC, wdigger commented on common/rect.h
> +#ifdef __cplusplus
At this point project contains many files with randomly (historically?) fragmented linked code. You systematically make decisions which worsen this situation.

2020-07-30 18:22 UTC, wdigger commented on common/rect.h
> +#ifdef __cplusplus
Done.

2020-07-30 21:27 UTC, OmniBlade approved these changes

2020-07-30 21:28 UTC, merged