Backport use of RandomClass to TD.
TheAssemblyArmada/Vanilla-Conquer pull request #763
Opened 2022-04-08 20:04 UTC by OmniBlade

Most calls to random will now use a build in random generator in TD like they do in RA making "randomness" deterministic across platforms. Built upon #742 which will need to be merged first.

2022-04-25 23:31 UTC, giulianobelinassi requested changes
Please rebase with the memory-related stuff from RA PR. Else than that, everything seems mostly fine.

2022-04-25 23:31 UTC, giulianobelinassi commented on redalert/queue.cpp
> +                fc.Write(buffer, strlen(buffer));
IMHO, Write should accept a printf-like format string to avoid such things. This also removes the need of additional buffers, which reduces the chance of memory errors related to that.

2022-04-25 23:31 UTC, giulianobelinassi commented on tiberiandawn/function.h
> +//#define Random_Pick(low, high) Random_Picky((low), (high), __FILE__, __LINE__)
Why this macro been commented out?

2022-04-25 23:31 UTC, giulianobelinassi commented on tiberiandawn/netdlg.cpp
> +    srand(time(NULL));
Why initialize it with time(NULL)?

2022-04-26 08:45 UTC, OmniBlade commented on tiberiandawn/function.h
> +//#define Random_Pick(low, high) Random_Picky((low), (high), __FILE__, __LINE__)
Replaced with template code below.

2022-04-26 08:45 UTC, OmniBlade commented on tiberiandawn/netdlg.cpp
> +    srand(time(NULL));
Original code calls `randomize()` which is is what PG commented out and which pretty much just does `srand(time(NULL))`, basically set the CRT rand to a random initial value.

2022-04-26 12:22 UTC, giulianobelinassi approved these changes

2022-04-26 13:10 UTC, merged