Avoid structure padding in the PCX read/write code
TheAssemblyArmada/Vanilla-Conquer pull request #766
Opened 2022-05-24 18:36 UTC by ccawley2011

On RISC OS, as well as with some other older ARM toolchains, structures are padded for alignment, however the PCX code expects these structures to be a specific size.

2022-05-24 22:05 UTC, OmniBlade approved these changes

2022-05-24 22:07 UTC, OmniBlade requested changes

2022-05-24 22:07 UTC, OmniBlade commented on common/filepcx.h
> +#pragma pack(1)
I was going to approve this, but I'd rather see `#pragma pack(push, 1)` and `#pragma pack(pop)` pairs which will restore the packing to whatever it was before the push rather than to the default compiler packing.

2022-05-24 23:56 UTC, ccawley2011 commented on common/filepcx.h
> +#pragma pack(1)
OK, done.

2022-05-25 09:12 UTC, OmniBlade approved these changes

2022-05-25 09:12 UTC, merged