Fix unaligned accesses and tweak some stuff for non-standard systems
TheAssemblyArmada/Vanilla-Conquer pull request #776
Opened 2022-06-26 15:50 UTC by giulianobelinassi

Systems running old ARM systems (ARM7, ARM9) has issues when accessing
unaligned addresses, resulting in swapped values. This commit fixes most
(if not all) of the issues regarding Tiberian Dawn.

There is still unaligned access warnings on BigShpBuffer, but that is not
an issue because althrough it reads/writes wrong value in memory, this is
correctly swapped in the CPU.

This commit also fixes issues with obsucure filesystem implementations,
like fseek being slow when it should return imediatelly and not finding
upper-case files on FAT32.

This also fixes a leak on Tiberian Dawn scorescreen.

Signed-off-by: Giuliano Belinassi <giuliano.belinassi@gmail.com>

2022-06-26 19:26 UTC, OmniBlade requested changes

2022-06-26 19:26 UTC, OmniBlade commented on common/crc.cpp
> +            memcpy(&l, longptr++, sizeof(int32_t));
If you use the `cstring` include, you should use `std::memcpy` as not all implementations guarantee that header will expose it in the global namespace. Alternatively use `string.h` header which does.

2022-06-26 19:26 UTC, OmniBlade commented on tiberiandawn/init.cpp
> +        strcat(scan_path, "sc*.mix");
How come the case is changed here?

2022-06-26 19:26 UTC, OmniBlade commented on tiberiandawn/loaddlg.cpp
> +                sprintf(fname, "savegame.%03d", game_num);
How come the case is changed here?

2022-06-26 20:19 UTC, giulianobelinassi commented on tiberiandawn/init.cpp
> +        strcat(scan_path, "sc*.mix");
For some reason, some implementations (the Nintendo DS, for instance) isn't happy about uppercase wildcards when finding files, even if the filesystem should be case-insensitive (FAT32).

I can remove this from the PR if you'd prefer.

2022-06-26 20:19 UTC, giulianobelinassi commented on tiberiandawn/loaddlg.cpp
> +                sprintf(fname, "savegame.%03d", game_num);
See above comment.

2022-06-27 14:36 UTC, OmniBlade approved these changes

2022-07-08 21:37 UTC, merged