Updated macOS workflow to build "universal 2" binaries.
TheAssemblyArmada/Vanilla-Conquer pull request #802
Opened 2022-07-16 14:05 UTC by MLipfert1

I updated the macOS workflow:

- Exchanged the deprecated macOS version 10.15 with 12 (Montery).
- Adjusted cmake command to build "Universal 2" binaries. Universal 2 means x64_64 and ARM64 combined.
- Exchanged HomeBrew with MacPorts.

HomeBrew is not capable of installing universal libraries that are required to build "universal 2" binaries. So the workflow will setup MacPorts and the required libraries. This updated workflow will require more time to complete (around 50 minutes), because the universal libraries have to be compiled also by MacPorts, but the result will be real "Universal 2" versions of VanillaTD and VanillaRA. The applications will run natively on former Intel-based Macs and the new Apple Silicon Macs.

2022-07-16 23:18 UTC, OmniBlade requested changes
While I approve far more of the use of macports given I strongly disagree with many of the design decisions of homebrew and was mainly using it because it comes preinstalled on the github container, the increase in build time is a hard pill to swallow.

2022-07-16 23:18 UTC, OmniBlade commented on .github/workflows/macos.yml
> +        sudo port install imageMagick -N
It looks like imagemagick gets built by macports, perhaps still installing it via brew would improve the build time somewhat as ~50mins is considerably out of step with other builds and is almost all down to dependency installation.

2022-07-17 07:17 UTC, MLipfert1 commented
ImageMagick is installed as binary package by MacPorts in only a few seconds. Most time consuming is the dependency tree for openal-soft.

Unfortunately, I do not see a possibility to reduce the dependency tree. The port files are configured by default to install bare minimum libraries (without additional and optional tools and so on).

2022-07-18 12:04 UTC, OmniBlade commented
I would say that seems to be a reasonable compromise for the time being. I'm also investigating docker containers using osxcross to build macOS targets that could be preloaded with the libraries we require to greatly reduce build time. Alternatively could we cache the macports tree and only install and populate it if its not restored from cache?

2022-07-18 13:09 UTC, MLipfert1 commented
I have created a second PR #816 for the additional macOS workflow. If you want to approve the second one, we can close this one here.

I am not that familiar with Github workflows yet, but I read some github docs about caching, because I thought the same. When I have understood the docs correctly, they do not intend to use caching for the dependencies. The reason might be, that the dependencies could be updated also on their repositories and it is in general intended to always get the latest ones (security updates).

2022-07-18 14:50 UTC, OmniBlade commented
Hmm, could we use conditions at the top level so the job runs or doesn't based on if its a PR or a commit to vanilla for example? The same way the development release is handled, but for the entire job so it builds the universal for the merged commit, but builds the faster. I've never tried that before so I don't actually know and my workflow knowledge is just based on a combo of copy and paste and a bit of trial and error.

Also, I don't know if you are aware, but there is no need to open a separate PR if you want to add an improvement to and existing one or rework it. In the former case, just push more commits to the same branch, in the latter, you can amend commits and force push the branch.

2022-07-18 15:00 UTC, MLipfert1 commented
I think that is possible to enable the triggers only for specific branches. I will try to enable the PR trigger for the vanilla branch for the universal workflow and the push trigger for all other branches and the intel-only workflow.

You are right. With amend and force push it should be possible to completely replace commits. I will try it then.

2022-09-07 19:55 UTC, MLipfert1 commented
I have just updated the branch with a new version of the macOS workflow. It is using now MacPorts for building the universal libraries that are required to compile universal binaries, but caches them also.

The cache is invalidated when it is not accessed in 7 days (by GitHub itself) or when a new version of dylibbundler, openal-soft or libsdl2 is available on MacPorts.

I took a brief test of this new workflow. When the cache is not available it took 35 minutes to complete and with cache available only 13 minutes.

2022-09-09 21:40 UTC, OmniBlade approved these changes
Okay, lets go for this then and not let perfect be the enemy of good.

2022-09-09 21:41 UTC, merged