Updates TD save code to use user data folders.
TheAssemblyArmada/Vanilla-Conquer pull request #827
Opened 2022-08-11 21:56 UTC by OmniBlade

2022-08-11 22:06 UTC, giulianobelinassi requested changes

2022-08-11 22:06 UTC, giulianobelinassi commented on tiberiandawn/loaddlg.cpp
> +                                ; // Copy string
This code resembles some code written by me (redalert/loaddlg.cpp:561).  Please refactor that into a common function.

2022-08-11 22:36 UTC, OmniBlade commented on tiberiandawn/loaddlg.cpp
> +                                ; // Copy string
I copy/pasted it from the RA load dialog as I assumed it fixed a bug you came upon in your DSi porting.

2022-10-13 14:53 UTC, tomsons26 commented on redalert/conquer.cpp
> +                sprintf(buffer, "Ins�rez le %s", _cd_name[cd]);
mmm?

2022-10-13 15:36 UTC, OmniBlade commented on redalert/conquer.cpp
> +                sprintf(buffer, "Ins�rez le %s", _cd_name[cd]);
Fixes an accidental unicode change from 6008d34bedc5f4fd445ad1a078c5fb1fa6cee3d2.

2022-10-17 13:07 UTC, giulianobelinassi approved these changes

2022-10-17 13:18 UTC, merged