Add big endian fixes for TD
TheAssemblyArmada/Vanilla-Conquer pull request #828
Opened 2022-08-17 22:32 UTC by giulianobelinassi

Mainly ported from Arczi's Amiga port and the attempted Nintendo 64
port.

2022-08-20 22:40 UTC, arczi84 approved these changes
Looks fine

2022-08-20 22:52 UTC, arczi84 reviewed
Ok.

2022-08-24 15:21 UTC, ccawley2011 commented on tiberiandawn/defines.h
> +#endif
This seems to be different from the other changes in this file. Was that intentional?

2022-08-24 15:21 UTC, ccawley2011 commented on common/crc.cpp
> +            l = le32toh(l);
Would it be worth having a macro that encapsulates these three lines?

2022-08-24 16:09 UTC, arczi84 commented on tiberiandawn/defines.h
> +#endif
Hmm, that's indeed odd. Should be revesed...  Haven't noticed wrong colors though.

2022-08-24 16:17 UTC, giulianobelinassi commented on tiberiandawn/defines.h
> +#endif
@arczi84 How is this line on your amiga branch?

2022-08-27 18:44 UTC, arczi84 approved these changes

2022-08-27 18:44 UTC, arczi84 commented on tiberiandawn/defines.h
> +#endif
It's int
PlayerColorType : signed int

2022-08-27 18:44 UTC, arczi84 commented on tiberiandawn/defines.h
> +#endif
typedef enum PlayerColorType : signed char
is original the code

2022-08-27 18:44 UTC, arczi84 commented on common/crc.cpp
> +            l = le32toh(l);
You can do whatever you like to make this cleaner as long it doesn't break anything.

2022-08-29 10:30 UTC, giulianobelinassi commented on tiberiandawn/defines.h
> +#endif
I see. This is indeed reversed.

2022-09-27 10:15 UTC, OmniBlade requested changes
Overall I'd like to get this merged as it opens up portability to several older consoles to support big endian, just a few clarifications needed.

2022-09-27 10:15 UTC, OmniBlade commented on common/wwstd.h
> +#define MAKE_LONG(a, b) ((long)((b)&0x0000FFFFL)) | ((long)(a) << 16)
Lets keep it the same as the updated code below and make this int despite the macro referring to long as long isn't 32bit on all platforms.

2022-09-27 10:15 UTC, OmniBlade commented on tiberiandawn/defines.h
> +#endif
Why are all these extended to int for big endian? Issues with aligned access?

2022-09-27 18:57 UTC, arczi84 commented on common/wwstd.h
> +#define MAKE_LONG(a, b) ((long)((b)&0x0000FFFFL)) | ((long)(a) << 16)
Yes, int should also work on BE.

2022-12-26 22:53 UTC, arczi84 commented on tiberiandawn/defines.h
> +#endif
Chars are swapped on big endian, I don't know a better solution for this.

2023-02-23 12:55 UTC, OmniBlade commented
Closing as this PR is superceded by work done by @isojalka

2023-02-23 12:55 UTC, closed without merging