File enumeration for posix platforms
TheAssemblyArmada/Vanilla-Conquer pull request #92
Opened 2020-08-05 08:06 UTC by wdigger

2020-08-05 08:42 UTC, hifi requested changes
As only one of these can be compiled in at a time the abstraction isn't necessarily.

2020-08-05 08:46 UTC, wdigger commented
Formally - yes, but it's just a for good C++ style - public interface, private implementation and so on.

2020-08-05 16:26 UTC, hifi commented on common/file.cpp
> +    Find_File_Data* ff_win = Find_File_Data::Construct();
Your arguments are reasonable and the implementations are good.

Though, can the `_win` postfix be removed from this variable and is `Find_File_Data::Construct` the best naming convention we can have for platform agnostic construction?

2020-08-05 18:55 UTC, wdigger commented on common/file.cpp
> +    Find_File_Data* ff_win = Find_File_Data::Construct();
Name fixed.
Factory method name changed, have no idea about unified naming, but in this case I use the same manner as in VideoSurface.
If there are ideas, then it can be changed later.

2020-08-06 04:34 UTC, hifi approved these changes
Windows version works fine and since POSIX isn't yet a CI tested target I tested it compiles on Linux so it's good enough for now.

2020-08-06 04:34 UTC, merged