Fixed radar remap for grey
TheAssemblyArmada/Vanilla-Conquer pull request #924
Opened 2023-05-24 16:38 UTC by tore29

In VC currently it shows a green colour for grey players on the radar. 

Current VC
![vcincorrectradarcolors](https://github.com/TheAssemblyArmada/Vanilla-Conquer/assets/3741094/0e530830-aeb3-4287-a11a-8347ab102e71)

As it looks like in C&C95 (using Nyerguds' 1.06 here)
![cccolors](https://github.com/TheAssemblyArmada/Vanilla-Conquer/assets/3741094/2020946e-dcb0-478c-a2df-4b816f2fdc1c)

How it looks like with this pull request
![vcfixedradarcolors](https://github.com/TheAssemblyArmada/Vanilla-Conquer/assets/3741094/791d91f7-cb63-4b8c-8527-61d57999d5b7)

2023-05-26 20:59 UTC, OmniBlade requested changes

2023-05-26 20:59 UTC, OmniBlade commented on tiberiandawn/house.cpp
> +
Nit pick, but loose the extra line break as its out of style with the rest of the switch block.

2023-05-26 22:46 UTC, tore29 commented on tiberiandawn/house.cpp
> +
Fixed

2023-05-27 21:42 UTC, OmniBlade approved these changes

2023-05-27 21:42 UTC, merged