Fix a narrowing conversion
TheAssemblyArmada/Vanilla-Conquer pull request #964
Opened 2024-03-20 12:42 UTC by th-otto

2024-04-15 13:57 UTC, OmniBlade requested changes
Comments apply to both games code, seems like a lot of changes to just silence a warning?

2024-04-15 13:57 UTC, OmniBlade commented on redalert/defines.h
> +#define PARM_PLAYTEST 0xF7DDC227UL // "PLAYTEST"
uint32_t is not unsigned long on all platforms.

2024-04-15 13:57 UTC, OmniBlade commented on redalert/target.h
> +        Target.Sub.Mantissa = (1UL << TARGET_MANTISSA) - 1;
I don't think this is equivalent?

2024-04-15 13:57 UTC, OmniBlade commented on tiberiandawn/init.cpp
> +uint32_t Obfuscate(char const* string)
The long type needs to go as its width varies between platforms but it should just change to int to match the ra code?

2024-04-15 14:33 UTC, th-otto commented
It's not only to get rid of the warning. Obfuscate() currently operates on an int, but in TD returns a long (unlike RA, which currently returns an int). Comparing that to a constant like 0xF7DDC227 may fail if the function actually returned 0xFFFFFFFFF7DDC227 because it was sign-extended to long. The only safe way is to declare them to return unsigned int (or uint32_t in this case), since this is what they actually calculate.

2024-06-12 08:25 UTC, OmniBlade commented
I'd be happy to see it changed to unsigned int in both cases.

2026-07-14 10:17 UTC, OmniBlade approved these changes
Most of the change made in this PR have been merged as part of other work, the remaining fixes for target mantissa still look useful however.

2026-07-14 10:18 UTC, merged